/* ============================================================================
 * EXTRACT TEAMS — rebuild src/data/teams.json from the site's own player data.
 *
 *   node tools/extract-teams.mjs [--dry] [--size 24]
 *
 * WHY THIS EXISTS
 *
 * teams.json says at the top that it was generated by this file. It was not in
 * the repository, so nobody could re-run it, and the file it produced had gone
 * wrong in a way nobody could check.
 *
 * WHAT WAS WRONG WITH THE OLD OUTPUT
 *
 * Every squad had been cut to twenty players, and the cut was not by ability.
 * Manchester City 2018 — labelled "Guardiola's peak" — shipped without David
 * Silva (90), Bernardo Silva (89), Phil Foden (87) or Leroy Sané (85), while
 * keeping Luke Bolton (66), an academy full-back who never played a league
 * game for the club. Manchester United 1999, the Treble side, shipped without
 * Paul Scholes. And because the eleven is picked by rating, the missing men
 * were not merely absent from the bench: they were absent from the team, and
 * a squad number that should have belonged to David Silva belonged to a
 * teenager instead.
 *
 * Every name in the old file does at least belong to the club and season it
 * was filed under — the fault was entirely in which twenty were kept.
 *
 * WHAT THIS DOES
 *
 * Nothing invented. Every player, and every one of his ratings, is copied out
 * of the club-and-season block he actually belongs to in ../src/data.js. The
 * squad is then cut BY ABILITY, with enough of each position guaranteed that
 * the eleven can always be picked without putting somebody absurdly out of
 * place — which is the other half of the Luke Bolton problem.
 *
 * WHAT IT DELIBERATELY DOES NOT TOUCH
 *
 *   - The team LIST, and each team's note, short name, playing style and home
 *     advantage. Those are editorial choices, not data, and they are read back
 *     out of the existing teams.json and preserved exactly.
 *   - Any existing player's `creativity` and `balance`. Those two are NOT in
 *     ../src/data.js and cannot be recovered from it: no formula in the site's
 *     own code reproduces them. They are real values from some earlier
 *     process, the engine has been balanced against them, and overwriting them
 *     with a guess would be exactly the kind of invention this tool exists to
 *     stop. So a player who is already in teams.json keeps his, verbatim.
 *
 *     A player being RESTORED has no stored pair, and the engine cannot run
 *     without them — creativity drives passing, vision and finishing; balance
 *     drives agility and acceleration. Those, and only those, are filled from
 *     a least-squares fit against all 720 existing players (R² 0.967 and
 *     0.946). The tool reports every player it had to do this for, so they can
 *     be corrected by hand.
 * ========================================================================== */

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = resolve(root, "../src/data.js");
const TARGET = join(root, "src/data/teams.json");

const args = process.argv.slice(2);
const dry = args.includes("--dry");
const sizeArg = args.indexOf("--size");
const SQUAD_SIZE = sizeArg >= 0 ? Number(args[sizeArg + 1]) : 24;

/* --- reading ../src/data.js ---------------------------------------------- */

/* Players are written as calls to a helper whose signature is, verbatim:
 *   p(name, pos, heading, fitness, strength, height, weight,
 *     leftFoot, rightFoot, speed, mentality, mentalityRating, overall, tier)
 * Squads are keyed "Club Name (YYYY)". */
const PLAYER = /p\(("(?:[^"\\]|\\.)*")\s*,\s*("(?:[^"\\]|\\.)*")\s*,([^)]*)\)/g;
const BLOCK = /"([^"]+?)\s*\((\d{4})\)"\s*:\s*\[([\s\S]*?)\n\s*\],/g;

function parseSquad(body) {
  const out = new Map();
  for (const m of body.matchAll(PLAYER)) {
    const rest = m[3].split(",").map((s) => s.trim());
    const n = (i) => Number(rest[i]);
    const overall = n(10);
    // A malformed or truncated call is skipped rather than guessed at.
    if (!Number.isFinite(overall)) continue;
    out.set(JSON.parse(m[1]), {
      name: JSON.parse(m[1]),
      pos: JSON.parse(m[2]),
      heading: n(0),
      fitness: n(1),
      strength: n(2),
      height: n(3),
      weight: n(4),
      leftFoot: n(5),
      rightFoot: n(6),
      speed: n(7),
      mentalityRating: n(9),
      overall,
    });
  }
  return out;
}

/* --- the two ratings ../src/data.js does not carry ------------------------ */

/* Least squares over all 720 players in the current teams.json. Used ONLY for
 * a player who is being restored and therefore has no stored value; see the
 * header. Coefficients are stated here rather than refitted at run time so
 * that two runs of this tool always produce the same file. */
const CREATIVITY_FIT = {
  base: -35.0249,
  bestFoot: 0.2623,
  weakFoot: 0.6753,
  mentalityRating: 0.2877,
  overall: 0.4913,
  speed: 0.0918,
  height: -0.1852,
};
const BALANCE_FIT = {
  base: 172.4408,
  strength: 0.149,
  height: -0.6046,
  weight: -0.3623,
  speed: 0.1462,
  fitness: 0.0833,
};

const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));

function estimateCreativity(d) {
  const best = Math.max(d.leftFoot, d.rightFoot);
  const weak = Math.min(d.leftFoot, d.rightFoot);
  const f = CREATIVITY_FIT;
  return clamp(
    Math.round(
      f.base +
        best * f.bestFoot +
        weak * f.weakFoot +
        d.mentalityRating * f.mentalityRating +
        d.overall * f.overall +
        d.speed * f.speed +
        d.height * f.height,
    ),
    30,
    99,
  );
}

function estimateBalance(d) {
  const f = BALANCE_FIT;
  return clamp(
    Math.round(
      f.base +
        d.strength * f.strength +
        d.height * f.height +
        d.weight * f.weight +
        d.speed * f.speed +
        d.fitness * f.fitness,
    ),
    30,
    99,
  );
}

/* --- picking a squad ------------------------------------------------------ */

/* Enough of each position that pickEleven() can fill any shape without
 * resorting to somebody wildly out of place. Two keepers is not optional:
 * docs/AUDIT.md records four squads that once shipped with none. */
const QUOTA = [
  { need: 2, of: ["GK"] },
  { need: 4, of: ["CB"] },
  { need: 3, of: ["FB"] },
  { need: 2, of: ["DM"] },
  { need: 3, of: ["CM"] },
  { need: 3, of: ["WG", "AM"] },
  { need: 3, of: ["FW"] },
];

/**
 * Cut the squad BY ABILITY, after guaranteeing position cover.
 *
 * The old file's central mistake was a cut that was neither: it dropped a
 * ninety-rated playmaker and kept a sixty-six-rated reserve full-back. Here
 * the quota is filled first — always with the best available for the position
 * — and every remaining place goes to the best player left, whoever he is.
 */
function pickSquad(all, size) {
  const byRating = [...all.values()].sort(
    (a, b) => b.overall - a.overall || a.name.localeCompare(b.name),
  );
  const taken = new Set();
  const squad = [];

  for (const { need, of } of QUOTA) {
    let filled = 0;
    for (const p of byRating) {
      if (filled >= need) break;
      if (taken.has(p.name) || !of.includes(p.pos)) continue;
      taken.add(p.name);
      squad.push(p);
      filled++;
    }
  }
  for (const p of byRating) {
    if (squad.length >= size) break;
    if (taken.has(p.name)) continue;
    taken.add(p.name);
    squad.push(p);
  }
  return squad.sort((a, b) => b.overall - a.overall || a.name.localeCompare(b.name));
}

/** What the picker sorts and labels on: the mean of the best eleven. */
const squadRating = (squad) =>
  Math.round(
    squad.slice(0, 11).reduce((t, p) => t + p.overall, 0) / Math.max(Math.min(squad.length, 11), 1),
  );

/* --- main ----------------------------------------------------------------- */

const source = await readFile(SOURCE, "utf8");
const existing = JSON.parse(await readFile(TARGET, "utf8"));

const blocks = new Map();
for (const m of source.matchAll(BLOCK)) {
  blocks.set(`${m[1].trim()} (${m[2]})`, parseSquad(m[3]));
}
console.log(`../src/data.js: ${blocks.size} club-season squads`);

const teams = [];
const restored = [];
const estimated = [];
const dropped = [];
const problems = [];

for (const team of existing.teams) {
  const key = `${team.club} (${team.season})`;
  const block = blocks.get(key);
  if (!block) {
    problems.push(`${key}: no squad in ../src/data.js — left exactly as it was`);
    teams.push(team);
    continue;
  }

  // Everything the old file already knew about this team's players, so that
  // creativity and balance survive untouched.
  const known = new Map(team.squad.map((p) => [p.name, p]));
  const picked = pickSquad(block, SQUAD_SIZE);

  const squad = picked.map((d) => {
    const was = known.get(d.name);
    if (!was) {
      restored.push(`${key}: ${d.name} (${d.pos} ${d.overall})`);
      estimated.push(`${d.name} — ${key}`);
    }
    return {
      name: d.name,
      pos: d.pos,
      overall: d.overall,
      mentalityRating: d.mentalityRating,
      heading: d.heading,
      fitness: d.fitness,
      strength: d.strength,
      speed: d.speed,
      leftFoot: d.leftFoot,
      rightFoot: d.rightFoot,
      // Preserved if we have it, fitted only if the player is new. See header.
      creativity: was ? was.creativity : estimateCreativity(d),
      balance: was ? was.balance : estimateBalance(d),
      height: d.height,
      weight: d.weight,
    };
  });

  for (const p of team.squad) {
    if (!block.has(p.name)) {
      dropped.push(`${key}: ${p.name} — not in that club's squad in ../src/data.js`);
    }
  }

  const keepers = squad.filter((p) => p.pos === "GK").length;
  if (keepers < 1) problems.push(`${key}: NO GOALKEEPER in the source squad`);

  teams.push({ ...team, rating: squadRating(squad), squad });
}

/* The match-day picker lists teams in file order and teams.ts documents that
 * order as "best first", so the file has to be re-sorted: restoring a squad's
 * missing stars changes its rating, and City 2018 moved from 85 to 87. */
teams.sort((a, b) => b.rating - a.rating || a.club.localeCompare(b.club) || a.season - b.season);

const out = {
  generated: "tools/extract-teams.mjs",
  source: "src/data.js",
  teams,
};

console.log(`\n${teams.length} teams, ${teams.reduce((t, x) => t + x.squad.length, 0)} players`);
console.log(`\nRESTORED (were missing from their own squad): ${restored.length}`);
for (const line of restored.slice(0, 40)) console.log(`  + ${line}`);
if (restored.length > 40) console.log(`  ...and ${restored.length - 40} more`);

console.log(`\nWERE IN teams.json BUT NOT IN THAT SQUAD: ${dropped.length}`);
for (const line of dropped) console.log(`  - ${line}`);

if (problems.length) {
  console.log(`\nPROBLEMS NEEDING A HUMAN: ${problems.length}`);
  for (const line of problems) console.log(`  ! ${line}`);
}

console.log(
  `\ncreativity/balance fitted for ${estimated.length} restored players ` +
    `(every other player keeps the exact values he already had).`,
);

if (dry) {
  console.log("\n--dry: nothing written");
} else {
  await writeFile(TARGET, `${JSON.stringify(out, null, 2)}\n`);
  console.log(`\nwritten -> ${TARGET}`);
}
