/* ============================================================================
 * THE TEAM LIST — real squads, pickable from the match-day screen.
 *
 * `teams.json` is generated by tools/extract-teams.mjs from the site's own
 * `src/data.js`: 2024's twenty Premier League squads plus sixteen sides worth
 * watching. Each carries the Manager's tactical style and home advantage, so
 * picking "Arsenal 2003" gives you Wenger's Invincibles playing Possession
 * football, not a generic side with their badge on it.
 *
 * Everything here is a straight read of that file into the Manager contract:
 * the same shape /Manager passes in, so the demo and the real integration
 * exercise exactly the same code path.
 * ========================================================================== */

import { pickEleven } from "../manager/lineup";
import type { ManagerClub, ManagerFixture, ManagerPlayer, ManagerPosition } from "../manager/contract";
import type { Formation } from "../core/types";
import teamsJson from "./teams.json";

export interface TeamEntry {
  id: string;
  club: string;
  season: number;
  note: string;
  shortName: string;
  style: string;
  homeAdvantage: number;
  /** Mean overall of the eleven best — what the picker sorts and labels on. */
  rating: number;
  squad: {
    name: string;
    pos: string;
    overall: number;
    mentalityRating: number;
    heading: number;
    fitness: number;
    strength: number;
    speed: number;
    leftFoot: number;
    rightFoot: number;
    creativity: number;
    balance: number;
    height: number;
    weight: number;
  }[];
}

const DATA = teamsJson as { teams: TeamEntry[] };

/** Kit colours per club, so a match looks like the match. Anything not listed
 *  falls back to a neutral pair chosen by home/away. */
const KITS: Record<string, { primary: string; secondary: string; number: string }> = {
  "Arsenal FC": { primary: "0xef0107", secondary: "0xffffff", number: "0xffffff" },
  "Aston Villa": { primary: "0x95bfe5", secondary: "0x670e36", number: "0x670e36" },
  "AFC Bournemouth": { primary: "0xda291c", secondary: "0x000000", number: "0xffffff" },
  "Blackburn Rovers": { primary: "0x009ee0", secondary: "0xffffff", number: "0xffffff" },
  "Brentford FC": { primary: "0xe30613", secondary: "0xffffff", number: "0xffffff" },
  "Brighton and Hove Albion": { primary: "0x0057b8", secondary: "0xffffff", number: "0xffffff" },
  "Burnley FC": { primary: "0x6c1d45", secondary: "0x99d6ea", number: "0xffffff" },
  "Chelsea FC": { primary: "0x034694", secondary: "0xffffff", number: "0xffffff" },
  "Crystal Palace": { primary: "0x1b458f", secondary: "0xc4122e", number: "0xffffff" },
  "Everton FC": { primary: "0x003399", secondary: "0xffffff", number: "0xffffff" },
  "Fulham FC": { primary: "0xffffff", secondary: "0x000000", number: "0x000000" },
  "Ipswich Town": { primary: "0x3a64a3", secondary: "0xffffff", number: "0xffffff" },
  "Leeds United": { primary: "0xffffff", secondary: "0x1d428a", number: "0x1d428a" },
  "Leicester City": { primary: "0x003090", secondary: "0xfdbe11", number: "0xffffff" },
  "Liverpool FC": { primary: "0xc8102e", secondary: "0x00b2a9", number: "0xffffff" },
  "Manchester City": { primary: "0x6cabdd", secondary: "0x1c2c5b", number: "0x1c2c5b" },
  "Manchester United": { primary: "0xda291c", secondary: "0xfbe122", number: "0xffffff" },
  "Newcastle United": { primary: "0x241f20", secondary: "0xffffff", number: "0xffffff" },
  "Nottingham Forest": { primary: "0xdd0000", secondary: "0xffffff", number: "0xffffff" },
  "Southampton FC": { primary: "0xd71920", secondary: "0xffffff", number: "0xffffff" },
  "Tottenham Hotspur": { primary: "0xffffff", secondary: "0x132257", number: "0x132257" },
  "West Ham United": { primary: "0x7a263a", secondary: "0x1bb1e7", number: "0xffffff" },
  "Wolverhampton Wanderers": { primary: "0xfdb913", secondary: "0x231f20", number: "0x231f20" },
};

const NEUTRAL_KIT = [
  { primary: "0xd11f2a", secondary: "0xffffff", number: "0xffffff" },
  { primary: "0x1746a2", secondary: "0xf2c14e", number: "0xffffff" },
];

/** Every team on the list, best first. */
export const teamList = (): TeamEntry[] => DATA.teams;

export function findTeam(id: string): TeamEntry | undefined {
  return DATA.teams.find((t) => t.id === id);
}

/** A team entry as the Manager would hand it over, with the eleven picked for
 *  the shape the user chose and the rest of the squad behind them. */
export function toManagerClub(
  entry: TeamEntry,
  formation: Formation,
  side: 0 | 1,
  styleOverride?: string,
): ManagerClub {
  const squad: ManagerPlayer[] = entry.squad.map((p, index) => ({
    id: `${entry.id}-${index}`,
    name: p.name,
    pos: p.pos as ManagerPosition,
    overall: p.overall,
    squadNumber: index + 1,
    mentalityRating: p.mentalityRating,
    morale: 60,
    attrs: {
      heading: p.heading,
      fitness: p.fitness,
      strength: p.strength,
      speed: p.speed,
      creativity: p.creativity,
      balance: p.balance,
      leftFoot: p.leftFoot,
      rightFoot: p.rightFoot,
      height: p.height,
      weight: p.weight,
    },
  }));

  const picked = pickEleven(squad, formation);
  return {
    id: entry.id,
    name: `${entry.club} ${entry.season}`,
    shortName: entry.shortName,
    formation: formation.id,
    style: styleOverride ?? entry.style,
    // The engine takes the squad in order: the eleven first, then the bench.
    squad: [...picked.eleven, ...picked.bench],
    kit: KITS[entry.club] ?? (NEUTRAL_KIT[side] as { primary: string; secondary: string; number: string }),
    homeAdvantage: entry.homeAdvantage,
    form: 0,
  };
}

export interface FixtureChoice {
  homeId: string;
  awayId: string;
  homeFormation: Formation;
  awayFormation: Formation;
  homeStyle?: string;
  awayStyle?: string;
  seed: string;
}

export function fixtureFrom(choice: FixtureChoice): ManagerFixture {
  const home = findTeam(choice.homeId) ?? (DATA.teams[0] as TeamEntry);
  const away = findTeam(choice.awayId) ?? (DATA.teams[1] as TeamEntry);
  return {
    seed: choice.seed,
    home: toManagerClub(home, choice.homeFormation, 0, choice.homeStyle),
    away: toManagerClub(away, choice.awayFormation, 1, choice.awayStyle),
    competition: "Friendly",
    weather: { pitchCondition: 0.35, rain: 0 },
  };
}
