import { ItemCategory, EquipSlot, Rarity } from './ItemTypes';
import type { ItemDefinition } from './ItemTypes';

/**
 * The Thornmarch item catalog.
 *
 * Adapted from the EndlessQuest Complete Item & Card Catalog. Two conversions are
 * applied so the catalog fits this build's continuous simulation model rather than
 * the dice model the source document assumed:
 *
 * - Weapon damage. The source gives dice (1d4+1, 2d6). Those are mapped onto this
 *   build's playtested damage band by rank, not by absolute value, via
 *   3 + 1.6 * diceMean. This preserves the catalog's relative ordering while keeping
 *   fights at the tuned length. The figure feeds the Pareto scale parameter in
 *   CombatMath, so it is a scale, not an expected value; the original dice are kept
 *   in sourceDice for traceability.
 * - Healing. The source assumes roughly 20 maximum hit points where this build uses
 *   100, so healing dice are converted by their expected value times five.
 *
 * Armour points become a damage-absorbed fraction. Morale, light radius, burn hours,
 * warmth, and durability are carried as data for systems that do not exist yet.
 *
 * Generated from the source catalog and then hand-edited for voice; treat this file
 * as source, not as build output.
 */
export const ITEMS: Record<string, ItemDefinition> = {
  chainmail: {
    id: 'chainmail',
    name: 'Chainmail Hauberk',
    category: ItemCategory.ARMOR,
    rarity: Rarity.ARTIFACT,
    description: 'A hauberk of riveted rings. Heavy, loud, and the reason its last owner nearly lived.',
    weight: 14.0,
    value: 100.0,
    consumable: false,
    armor: 0.32,
    slot: EquipSlot.BODY,
    durability: 150,
    tags: ['armor_clothing'],
  },
  fur_boots: {
    id: 'fur_boots',
    name: 'Fur-Lined Boots',
    category: ItemCategory.ARMOR,
    rarity: Rarity.RARE,
    description: 'Lined with something that was recently on an animal. Your feet stop being a problem you think about.',
    weight: 1.5,
    value: 25.0,
    consumable: false,
    armor: 0.08,
    slot: EquipSlot.FEET,
    warmth: 3.0,
    durability: 80,
    tags: ['armor_clothing'],
  },
  gambeson: {
    id: 'gambeson',
    name: 'Padded Gambeson',
    category: ItemCategory.ARMOR,
    rarity: Rarity.UNCOMMON,
    description: 'Layered linen, quilted and stinking. Cheap, warm, and it works.',
    weight: 4.0,
    value: 15.0,
    consumable: false,
    armor: 0.08,
    slot: EquipSlot.BODY,
    warmth: 2.0,
    durability: 90,
    tags: ['armor_clothing'],
  },
  iron_helmet: {
    id: 'iron_helmet',
    name: 'Iron Helmet',
    category: ItemCategory.ARMOR,
    rarity: Rarity.RARE,
    description: 'Solid iron with a narrow slot to see through. You will not hear things coming.',
    weight: 2.0,
    value: 40.0,
    consumable: false,
    armor: 0.16,
    slot: EquipSlot.HEAD,
    durability: 120,
    tags: ['armor_clothing'],
  },
  leather_armor: {
    id: 'leather_armor',
    name: 'Leather Armor',
    category: ItemCategory.ARMOR,
    rarity: Rarity.RARE,
    description: 'A full harness of hardened leather. The standard for anyone who walks the roads armed.',
    weight: 5.0,
    value: 35.0,
    consumable: false,
    armor: 0.16,
    slot: EquipSlot.BODY,
    warmth: 1.0,
    durability: 100,
    tags: ['armor_clothing'],
  },
  leather_boots: {
    id: 'leather_boots',
    name: 'Leather Boots',
    category: ItemCategory.ARMOR,
    rarity: Rarity.UNCOMMON,
    description: 'Resoled twice by somebody who knew how. They will see out the season if the season is kind.',
    weight: 1.0,
    value: 10.0,
    consumable: false,
    armor: 0.08,
    slot: EquipSlot.FEET,
    warmth: 1.0,
    durability: 70,
    tags: ['armor_clothing'],
  },
  leather_cap: {
    id: 'leather_cap',
    name: 'Leather Cap',
    category: ItemCategory.ARMOR,
    rarity: Rarity.UNCOMMON,
    description: 'A capped skull is a live skull, most days.',
    weight: 0.5,
    value: 8.0,
    consumable: false,
    armor: 0.08,
    slot: EquipSlot.HEAD,
    warmth: 1.0,
    durability: 50,
    tags: ['armor_clothing'],
  },
  leather_vest: {
    id: 'leather_vest',
    name: 'Leather Vest',
    category: ItemCategory.ARMOR,
    rarity: Rarity.UNCOMMON,
    description: 'Boiled hide over the chest. Turns a glancing blade, sometimes.',
    weight: 3.0,
    value: 20.0,
    consumable: false,
    armor: 0.08,
    slot: EquipSlot.BODY,
    warmth: 1.0,
    durability: 80,
    tags: ['armor_clothing'],
  },
  patched_cloak: {
    id: 'patched_cloak',
    name: 'Patched Cloak',
    category: ItemCategory.ARMOR,
    rarity: Rarity.UNCOMMON,
    description: 'Mended past the point of the original cloth. Breaks up your outline after dark.',
    weight: 1.0,
    value: 5.0,
    consumable: false,
    slot: EquipSlot.BODY,
    warmth: 1.0,
    durability: 40,
    tags: ['armor_clothing'],
  },
  plate_armor: {
    id: 'plate_armor',
    name: 'Plate Armor',
    category: ItemCategory.ARMOR,
    rarity: Rarity.ARTIFACT,
    description: 'Articulated plate. Nobody in the Thornmarch owns this honestly.',
    weight: 25.0,
    value: 200.0,
    consumable: false,
    armor: 0.48,
    slot: EquipSlot.BODY,
    durability: 200,
    tags: ['armor_clothing'],
  },
  studded_leather: {
    id: 'studded_leather',
    name: 'Studded Leather',
    category: ItemCategory.ARMOR,
    rarity: Rarity.RARE,
    description: 'Leather set with iron rivets. Heavier, and worth the weight.',
    weight: 6.0,
    value: 60.0,
    consumable: false,
    armor: 0.24,
    slot: EquipSlot.BODY,
    warmth: 1.0,
    durability: 110,
    tags: ['armor_clothing'],
  },
  wooden_shoes: {
    id: 'wooden_shoes',
    name: 'Wooden Shoes',
    category: ItemCategory.ARMOR,
    rarity: Rarity.COMMON,
    description: 'Clogs. They keep the wet out and take the skin off your heels doing it.',
    weight: 0.8,
    value: 3.0,
    consumable: false,
    slot: EquipSlot.FEET,
    durability: 40,
    tags: ['armor_clothing'],
  },
  wool_cloak: {
    id: 'wool_cloak',
    name: 'Wool Cloak',
    category: ItemCategory.ARMOR,
    rarity: Rarity.UNCOMMON,
    description: 'Good wool, still oily. Sheds rain better than anything else you will find.',
    weight: 1.5,
    value: 15.0,
    consumable: false,
    slot: EquipSlot.BODY,
    warmth: 2.0,
    durability: 60,
    tags: ['armor_clothing'],
  },
  wool_hat: {
    id: 'wool_hat',
    name: 'Wool Hat',
    category: ItemCategory.ARMOR,
    rarity: Rarity.COMMON,
    description: 'Greasy with lanolin, which is why it still turns rain. Most of the heat goes out of a man through his head.',
    weight: 0.3,
    value: 3.0,
    consumable: false,
    slot: EquipSlot.HEAD,
    warmth: 2.0,
    durability: 30,
    tags: ['armor_clothing'],
  },
  blood_ring: {
    id: 'blood_ring',
    name: 'Ring of the Red Pact',
    category: ItemCategory.ARTIFACT,
    rarity: Rarity.ARTIFACT,
    description: 'A red pact, worn on the hand. It makes you stronger. It also makes you keen to use it.',
    weight: 0.1,
    value: 350.0,
    consumable: false,
    boon: '+1 Strength',
    bane: 'Increasingly violent',
    tags: ['artifacts'],
  },
  charred_fingerbone: {
    id: 'charred_fingerbone',
    name: 'Charred Fingerbone',
    category: ItemCategory.ARTIFACT,
    rarity: Rarity.ARTIFACT,
    description: 'Someone\'s finger, burned black and kept. It warms when something is coming.',
    weight: 0.1,
    value: 100.0,
    consumable: false,
    boon: 'Grows warm near danger',
    bane: 'Burns wielder if held too long',
    tags: ['artifacts'],
  },
  glass_eye: {
    id: 'glass_eye',
    name: 'Glass Eye of the Old King',
    category: ItemCategory.ARTIFACT,
    rarity: Rarity.ARTIFACT,
    description: 'A blown-glass eye, clouded. You can see in full dark with it. Something is looking back down the same line.',
    weight: 0.1,
    value: 150.0,
    consumable: false,
    boon: 'See in total darkness',
    bane: 'Something sees through it',
    tags: ['artifacts'],
  },
  iron_bell: {
    id: 'iron_bell',
    name: 'Iron Bell That Rings Only in Fog',
    category: ItemCategory.ARTIFACT,
    rarity: Rarity.ARTIFACT,
    description: 'It rings only in fog, and never when you shake it. What it calls or drives off is not yours to choose.',
    weight: 0.5,
    value: 250.0,
    consumable: false,
    boon: 'Repels or attracts spirits',
    bane: 'Cannot control which',
    tags: ['artifacts'],
  },
  old_coin: {
    id: 'old_coin',
    name: 'Coin of the First King',
    category: ItemCategory.ARTIFACT,
    rarity: Rarity.ARTIFACT,
    description: 'A coin from a king nobody can name. It makes a man better at everything, and spends his years to do it.',
    weight: 0.1,
    value: 400.0,
    consumable: false,
    boon: '+1 to all attributes',
    bane: 'Ages 10% faster',
    tags: ['artifacts'],
  },
  sun_medallion: {
    id: 'sun_medallion',
    name: 'Tarnished Sun Medallion',
    category: ItemCategory.ARTIFACT,
    rarity: Rarity.ARTIFACT,
    description: 'Tarnished silver, a sun in relief. It closes wounds, and it makes a noise that only the dead can hear.',
    weight: 0.2,
    value: 200.0,
    consumable: false,
    boon: 'Heals 1d6 HP when worn',
    bane: 'Attracts monsters',
    tags: ['artifacts'],
  },
  weeping_stone: {
    id: 'weeping_stone',
    name: 'Weeping Stone',
    category: ItemCategory.ARTIFACT,
    rarity: Rarity.ARTIFACT,
    description: 'A stone that beads clean water every dawn. The dead follow water.',
    weight: 1.0,
    value: 100.0,
    consumable: false,
    boon: 'Produces clean water daily',
    bane: 'Attracts ghosts',
    tags: ['artifacts'],
  },
  wraith_cloak: {
    id: 'wraith_cloak',
    name: 'Wraith\'s Cloak',
    category: ItemCategory.ARTIFACT,
    rarity: Rarity.ARTIFACT,
    description: 'Grey cloth that hangs wrong. Wearing it, the dark ignores you. So, gradually, does your own memory.',
    weight: 1.0,
    value: 300.0,
    consumable: false,
    boon: '+2 stealth at night',
    bane: 'Slowly erases memories',
    tags: ['artifacts'],
  },
  ale: {
    id: 'ale',
    name: 'Mug of Ale',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'Thin and sour and it takes the edge off the dark.',
    weight: 0.5,
    value: 5.0,
    consumable: true,
    hunger: 5.0,
    thirst: 15.0,
    morale: 2.0,
    tags: ['food_drink'],
  },
  apple: {
    id: 'apple',
    name: 'Apple',
    category: ItemCategory.FOOD,
    rarity: Rarity.COMMON,
    description: 'Small, russeted, and going soft on one side. Somebody grew this on purpose once.',
    weight: 0.2,
    value: 2.0,
    consumable: true,
    hunger: 10.0,
    thirst: 5.0,
    morale: 1.0,
    tags: ['food_drink'],
  },
  bread: {
    id: 'bread',
    name: 'Bread',
    category: ItemCategory.FOOD,
    rarity: Rarity.COMMON,
    description: 'A dark loaf. The commonest good thing in the world.',
    weight: 0.5,
    value: 3.0,
    consumable: true,
    hunger: 25.0,
    tags: ['food_drink'],
  },
  cheese: {
    id: 'cheese',
    name: 'Hard Cheese',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'A wedge off a hard wheel, rind and all. It will keep longer than you will.',
    weight: 0.3,
    value: 10.0,
    consumable: true,
    hunger: 20.0,
    tags: ['food_drink'],
  },
  cooked_meat: {
    id: 'cooked_meat',
    name: 'Cooked Meat',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'Hot, and fat still on it. You had forgotten.',
    weight: 0.5,
    value: 12.0,
    consumable: true,
    hunger: 30.0,
    morale: 1.0,
    tags: ['food_drink'],
  },
  cooked_mushroom: {
    id: 'cooked_mushroom',
    name: 'Cooked Mushroom',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'Fried black in whatever fat there was. The trick with mushrooms is knowing, and then cooking them anyway.',
    weight: 0.1,
    value: 5.0,
    consumable: true,
    hunger: 10.0,
    tags: ['food_drink'],
  },
  dried_meat: {
    id: 'dried_meat',
    name: 'Dried Meat',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'Salted and hung until it went hard. Keeps for a season.',
    weight: 0.3,
    value: 8.0,
    consumable: true,
    hunger: 20.0,
    tags: ['food_drink'],
  },
  fresh_bread: {
    id: 'fresh_bread',
    name: 'Fresh Bread',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'Still warm in the middle. You had forgotten this was a thing that happened.',
    weight: 0.5,
    value: 5.0,
    consumable: true,
    hunger: 30.0,
    morale: 1.0,
    tags: ['food_drink'],
  },
  hard_biscuit: {
    id: 'hard_biscuit',
    name: 'Hard Biscuit',
    category: ItemCategory.FOOD,
    rarity: Rarity.COMMON,
    description: 'Twice-baked and hard enough to break a tooth on. Soldiers live on these and complain about it forever.',
    weight: 0.2,
    value: 2.0,
    consumable: true,
    hunger: 15.0,
    tags: ['food_drink'],
  },
  herb_tea: {
    id: 'herb_tea',
    name: 'Herb Tea',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'Bitter, and it puts warmth back into your hands.',
    weight: 0.2,
    value: 5.0,
    consumable: true,
    hunger: 5.0,
    thirst: 20.0,
    morale: 1.0,
    tags: ['food_drink'],
  },
  honey_cake: {
    id: 'honey_cake',
    name: 'Honey Cake',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'Somebody made this for a saint\u2019s day. It is the best thing you have eaten in a year.',
    weight: 0.3,
    value: 8.0,
    consumable: true,
    hunger: 20.0,
    morale: 2.0,
    tags: ['food_drink'],
  },
  mead: {
    id: 'mead',
    name: 'Mug of Mead',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'Honey gone strong. Warms you through and makes the ground look further away than it is.',
    weight: 0.5,
    value: 8.0,
    consumable: true,
    hunger: 10.0,
    thirst: 10.0,
    morale: 2.0,
    tags: ['food_drink'],
  },
  mushroom: {
    id: 'mushroom',
    name: 'Wild Mushroom',
    category: ItemCategory.FOOD,
    rarity: Rarity.COMMON,
    description: 'You know most of these. Most.',
    weight: 0.1,
    value: 3.0,
    consumable: true,
    hunger: 5.0,
    tags: ['food_drink'],
  },
  raw_meat: {
    id: 'raw_meat',
    name: 'Raw Meat',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'It needs a fire. Eating it as it is will cost you more than it gives.',
    weight: 0.5,
    value: 5.0,
    consumable: true,
    hunger: 10.0,
    morale: -2.0,
    tags: ['food_drink'],
  },
  salted_fish: {
    id: 'salted_fish',
    name: 'Salted Fish',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'Stiff as a board and salty enough to hurt. It travels, which is the whole point of it.',
    weight: 0.4,
    value: 12.0,
    consumable: true,
    hunger: 25.0,
    thirst: 5.0,
    tags: ['food_drink'],
  },
  stale_bread: {
    id: 'stale_bread',
    name: 'Stale Bread',
    category: ItemCategory.FOOD,
    rarity: Rarity.COMMON,
    description: 'Hard enough to need soaking. It is still bread.',
    weight: 0.5,
    value: 1.0,
    consumable: true,
    hunger: 15.0,
    morale: -1.0,
    tags: ['food_drink'],
  },
  stew: {
    id: 'stew',
    name: 'Bowl of Stew',
    category: ItemCategory.FOOD,
    rarity: Rarity.UNCOMMON,
    description: 'Someone cooked this for someone. It is hot the whole way down.',
    weight: 1.0,
    value: 15.0,
    consumable: true,
    hunger: 35.0,
    thirst: 10.0,
    fatigue: 5.0,
    morale: 1.0,
    tags: ['food_drink'],
  },
  waterskin: {
    id: 'waterskin',
    name: 'Waterskin (Full)',
    category: ItemCategory.FOOD,
    rarity: Rarity.COMMON,
    description: 'Water, or near enough. It has a taste but it has never killed you.',
    weight: 1.0,
    value: 4.0,
    consumable: true,
    thirst: 40.0,
    tags: ['food_drink'],
  },
  waterskin_empty: {
    id: 'waterskin_empty',
    name: 'Empty Waterskin',
    category: ItemCategory.FOOD,
    rarity: Rarity.COMMON,
    description: 'Empty. A waterskin you cannot fill is just weight.',
    weight: 0.3,
    value: 1.0,
    consumable: false,
    tags: ['food_drink'],
  },
  wild_berries: {
    id: 'wild_berries',
    name: 'Wild Berries',
    category: ItemCategory.FOOD,
    rarity: Rarity.COMMON,
    description: 'Hedgerow fruit the birds missed. Barely food, but food.',
    weight: 0.2,
    value: 2.0,
    consumable: true,
    hunger: 10.0,
    thirst: 10.0,
    tags: ['food_drink'],
  },
  candle: {
    id: 'candle',
    name: 'Tallow Candle',
    category: ItemCategory.LIGHT,
    rarity: Rarity.COMMON,
    description: 'Tallow, and it smells like what it is made from.',
    weight: 0.1,
    value: 1.0,
    consumable: false,
    lightRadius: 1.0,
    burnHours: 4.0,
    tags: ['light_sources'],
  },
  firewood: {
    id: 'firewood',
    name: 'Bundle of Firewood',
    category: ItemCategory.LIGHT,
    rarity: Rarity.COMMON,
    description: 'Cut and bundled. A fire is the difference between a night and an ordeal.',
    weight: 3.0,
    value: 2.0,
    consumable: false,
    lightRadius: 4.0,
    burnHours: 6.0,
    tags: ['light_sources'],
  },
  oil_lamp: {
    id: 'oil_lamp',
    name: 'Oil Lamp',
    category: ItemCategory.LIGHT,
    rarity: Rarity.UNCOMMON,
    description: 'A clay dish, a wick, and whatever oil you can spare. Burns low and steady and shows everything where you are.',
    weight: 0.5,
    value: 10.0,
    consumable: false,
    lightRadius: 4.0,
    burnHours: 8.0,
    tags: ['light_sources'],
  },
  torch: {
    id: 'torch',
    name: 'Pitch Torch',
    category: ItemCategory.LIGHT,
    rarity: Rarity.COMMON,
    description: 'Pitch and rag on a stick. Fire keeps most things at the edge of the light.',
    weight: 0.3,
    value: 1.0,
    consumable: false,
    lightRadius: 3.0,
    burnHours: 1.0,
    tags: ['light_sources'],
  },
  antler: {
    id: 'antler',
    name: 'Deer Antler',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Shed, not cut. Good for a knife handle, and worth something to a man who makes them.',
    weight: 1.0,
    value: 15.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  bear_claw: {
    id: 'bear_claw',
    name: 'Bear Claw',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Longer than your thumb. Whoever took it did not take the rest of the bear.',
    weight: 0.2,
    value: 20.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  bone: {
    id: 'bone',
    name: 'Animal Bone',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.COMMON,
    description: 'Long bone, cracked at one end. Bone takes an edge, if you have the patience.',
    weight: 0.5,
    value: 3.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  clay: {
    id: 'clay',
    name: 'Wet Clay',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.COMMON,
    description: 'Grey and heavy and still wet from the bank. It will be a pot or it will be nothing.',
    weight: 4.0,
    value: 3.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  cloth: {
    id: 'cloth',
    name: 'Bolt of Cloth',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Undyed linen, close-woven. Bandages, or a shirt, or a shroud.',
    weight: 1.0,
    value: 10.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  feather: {
    id: 'feather',
    name: 'Feather',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.COMMON,
    description: 'A pinion feather off something large. Fletching, if you have the shafts.',
    weight: 0.1,
    value: 2.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  flour: {
    id: 'flour',
    name: 'Sack of Flour',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Ground fine and only a little gritty. Flour is a village\u2019s whole year in a sack.',
    weight: 2.0,
    value: 8.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  fur: {
    id: 'fur',
    name: 'Animal Pelt',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Scraped and drying, stiff at the edges. Warm, once it is worked soft.',
    weight: 2.0,
    value: 12.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  grain: {
    id: 'grain',
    name: 'Sack of Grain',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Barley, unmilled. Somebody was going to eat this through the winter.',
    weight: 3.0,
    value: 10.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  herbs: {
    id: 'herbs',
    name: 'Medicinal Herbs',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Whatever the hedgerow gave up that is worth drying.',
    weight: 0.1,
    value: 8.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  honey: {
    id: 'honey',
    name: 'Jar of Honey',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Dark, and set solid with the comb still in it. It keeps forever and it closes wounds.',
    weight: 0.5,
    value: 20.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  iron_ingot: {
    id: 'iron_ingot',
    name: 'Iron Ingot',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.RARE,
    description: 'A bar of worked iron, heavier than it looks. This is what a blade is before it is a blade.',
    weight: 1.0,
    value: 30.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Iron Ore',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Rust-red rock, dense in the hand. Useless until somebody with a furnace wants it.',
    weight: 3.0,
    value: 10.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  leather: {
    id: 'leather',
    name: 'Tanned Leather',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Tanned, oiled, and cut square. Half the things a man wears out here start as this.',
    weight: 1.0,
    value: 15.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  poison_herb: {
    id: 'poison_herb',
    name: 'Nightshade',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Deadly nightshade. The berries look like fruit, which is the trouble.',
    weight: 0.1,
    value: 20.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  salt: {
    id: 'salt',
    name: 'Bag of Salt',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Grey crystals, damp in the corners. Salt is what stands between a good year and a hungry one.',
    weight: 0.5,
    value: 10.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  sand: {
    id: 'sand',
    name: 'Bag of Sand',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.COMMON,
    description: 'Fine river sand, washed clean. Glass, or a scouring, or a grave marker.',
    weight: 3.0,
    value: 2.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  stone: {
    id: 'stone',
    name: 'Cut Stone',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Squared and dressed on four faces. Somebody cut this to build with and never built.',
    weight: 4.0,
    value: 6.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  wax: {
    id: 'wax',
    name: 'Beeswax',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'A pale block that smells faintly of the hive. Candles, sealed jars, waxed thread.',
    weight: 0.3,
    value: 10.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  wolf_fang: {
    id: 'wolf_fang',
    name: 'Wolf Fang',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Yellowed and worn at the tip. Old wolf. It got old by being careful.',
    weight: 0.1,
    value: 8.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  wood: {
    id: 'wood',
    name: 'Bundle of Wood',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.COMMON,
    description: 'Split and seasoned, tied with cord. Fire, or a handle, or a splint.',
    weight: 3.0,
    value: 3.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  wool: {
    id: 'wool',
    name: 'Bundle of Wool',
    category: ItemCategory.MATERIAL,
    rarity: Rarity.UNCOMMON,
    description: 'Raw fleece, still carrying the smell of the animal. It will be warm long before it is clean.',
    weight: 1.0,
    value: 8.0,
    consumable: false,
    tags: ['resources_materials'],
  },
  antidote: {
    id: 'antidote',
    name: 'Antidote',
    category: ItemCategory.MEDICAL,
    rarity: Rarity.RARE,
    description: 'Rare herbs, carefully measured. Someone died learning the measure.',
    weight: 0.1,
    value: 25.0,
    consumable: true,
    uses: 1,
    tags: ['medical_supplies'],
  },
  bandage: {
    id: 'bandage',
    name: 'Clean Bandage',
    category: ItemCategory.MEDICAL,
    rarity: Rarity.COMMON,
    description: 'Clean strips, boiled once. Worth more out here than silver.',
    weight: 0.1,
    value: 3.0,
    consumable: true,
    hp: 12,
    uses: 1,
    tags: ['medical_supplies'],
  },
  burn_ointment: {
    id: 'burn_ointment',
    name: 'Burn Ointment',
    category: ItemCategory.MEDICAL,
    rarity: Rarity.UNCOMMON,
    description: 'Rendered fat and something green, in a horn pot. For when the fire wins.',
    weight: 0.2,
    value: 12.0,
    consumable: true,
    hp: 12,
    uses: 2,
    tags: ['medical_supplies'],
  },
  dirty_rag: {
    id: 'dirty_rag',
    name: 'Dirty Rag',
    category: ItemCategory.MEDICAL,
    rarity: Rarity.COMMON,
    description: 'Not clean. You use it anyway, and hope.',
    weight: 0.1,
    value: 1.0,
    consumable: true,
    uses: 1,
    tags: ['medical_supplies'],
  },
  feverfew: {
    id: 'feverfew',
    name: 'Feverfew Herb',
    category: ItemCategory.MEDICAL,
    rarity: Rarity.UNCOMMON,
    description: 'Small white flowers. The herbalists swear by it and they are mostly right.',
    weight: 0.1,
    value: 8.0,
    consumable: true,
    uses: 1,
    tags: ['medical_supplies'],
  },
  healing_salve: {
    id: 'healing_salve',
    name: 'Healing Salve',
    category: ItemCategory.MEDICAL,
    rarity: Rarity.UNCOMMON,
    description: 'Rendered fat and something green. Expensive, and it works.',
    weight: 0.2,
    value: 20.0,
    consumable: true,
    hp: 18,
    uses: 3,
    tags: ['medical_supplies'],
  },
  herbal_poultice: {
    id: 'herbal_poultice',
    name: 'Herbal Poultice',
    category: ItemCategory.MEDICAL,
    rarity: Rarity.UNCOMMON,
    description: 'Mashed herbs bound under cloth. Draws the rot out if you are lucky.',
    weight: 0.2,
    value: 10.0,
    consumable: true,
    hp: 25,
    uses: 1,
    tags: ['medical_supplies'],
  },
  needle_thread: {
    id: 'needle_thread',
    name: 'Needle & Thread',
    category: ItemCategory.MEDICAL,
    rarity: Rarity.UNCOMMON,
    description: 'A bone needle and waxed gut. Mends cloth. Mends worse than cloth, if your hands are steady.',
    weight: 0.1,
    value: 8.0,
    consumable: true,
    uses: 5,
    tags: ['medical_supplies'],
  },
  painkiller: {
    id: 'painkiller',
    name: 'Painkiller Tincture',
    category: ItemCategory.MEDICAL,
    rarity: Rarity.UNCOMMON,
    description: 'Willow bark steeped down to a bitter syrup. Takes the edge off. Takes the edge off your judgement too.',
    weight: 0.1,
    value: 15.0,
    consumable: true,
    uses: 2,
    tags: ['medical_supplies'],
  },
  splint: {
    id: 'splint',
    name: 'Wooden Splint',
    category: ItemCategory.MEDICAL,
    rarity: Rarity.UNCOMMON,
    description: 'Two shaped staves and cord. For when the bone is wrong.',
    weight: 0.5,
    value: 5.0,
    consumable: true,
    uses: 1,
    tags: ['medical_supplies'],
  },
  makeshift_board: {
    id: 'makeshift_board',
    name: 'Makeshift Board',
    category: ItemCategory.SHIELD,
    rarity: Rarity.COMMON,
    description: 'A plank with a strap nailed across it. Better than an open arm.',
    weight: 1.5,
    value: 2.0,
    consumable: false,
    armor: 0.08,
    slot: EquipSlot.OFFHAND,
    durability: 20,
    tags: ['shields'],
  },
  reinforced_shield: {
    id: 'reinforced_shield',
    name: 'Reinforced Shield',
    category: ItemCategory.SHIELD,
    rarity: Rarity.RARE,
    description: 'Rimmed and bossed in iron. Built to be hit.',
    weight: 5.0,
    value: 30.0,
    consumable: false,
    armor: 0.24,
    slot: EquipSlot.OFFHAND,
    durability: 110,
    tags: ['shields'],
  },
  tower_shield: {
    id: 'tower_shield',
    name: 'Tower Shield',
    category: ItemCategory.SHIELD,
    rarity: Rarity.RARE,
    description: 'A wall you have to carry. Slow, and almost unkillable behind.',
    weight: 9.0,
    value: 60.0,
    consumable: false,
    armor: 0.32,
    slot: EquipSlot.OFFHAND,
    durability: 150,
    tags: ['shields'],
  },
  wooden_shield: {
    id: 'wooden_shield',
    name: 'Wooden Shield',
    category: ItemCategory.SHIELD,
    rarity: Rarity.UNCOMMON,
    description: 'Planks and a boss. It will take perhaps four good blows.',
    weight: 3.0,
    value: 10.0,
    consumable: false,
    armor: 0.16,
    slot: EquipSlot.OFFHAND,
    durability: 70,
    tags: ['shields'],
  },
  bedroll: {
    id: 'bedroll',
    name: 'Bedroll',
    category: ItemCategory.SURVIVAL,
    rarity: Rarity.UNCOMMON,
    description: 'Canvas and straw ticking. Sleep off the wet ground is sleep you keep.',
    weight: 1.5,
    value: 15.0,
    consumable: false,
    tags: ['survival_gear'],
  },
  blanket: {
    id: 'blanket',
    name: 'Wool Blanket',
    category: ItemCategory.SURVIVAL,
    rarity: Rarity.UNCOMMON,
    description: 'Coarse wool. It has somebody else\'s smell in it.',
    weight: 1.0,
    value: 8.0,
    consumable: false,
    tags: ['survival_gear'],
  },
  compass: {
    id: 'compass',
    name: 'Compass',
    category: ItemCategory.SURVIVAL,
    rarity: Rarity.RARE,
    description: 'A lodestone needle floating on water in a turned box. Rare, and worth what it costs.',
    weight: 0.2,
    value: 50.0,
    consumable: false,
    tags: ['survival_gear'],
  },
  map_fragment: {
    id: 'map_fragment',
    name: 'Map Fragment',
    category: ItemCategory.SURVIVAL,
    rarity: Rarity.RARE,
    description: 'A corner torn off something larger, with three place names on it and part of a river.',
    weight: 0.1,
    value: 25.0,
    consumable: false,
    tags: ['survival_gear'],
  },
  tent: {
    id: 'tent',
    name: 'Small Tent',
    category: ItemCategory.SURVIVAL,
    rarity: Rarity.RARE,
    description: 'Oiled canvas and poles. Walls, of a sort.',
    weight: 3.0,
    value: 30.0,
    consumable: false,
    tags: ['survival_gear'],
  },
  bucket: {
    id: 'bucket',
    name: 'Wooden Bucket',
    category: ItemCategory.TOOL,
    rarity: Rarity.COMMON,
    description: 'Staved and hooped, and it does not leak, which is more than most.',
    weight: 1.0,
    value: 4.0,
    consumable: false,
    tags: ['tools_utility'],
  },
  cooking_pot: {
    id: 'cooking_pot',
    name: 'Iron Cooking Pot',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'Blackened outside, scoured inside. Boiling is what makes bad water into water.',
    weight: 2.5,
    value: 15.0,
    consumable: false,
    tags: ['tools_utility'],
  },
  fishing_rod: {
    id: 'fishing_rod',
    name: 'Fishing Rod',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'Knotted cord, mended more than once. Set it right and the water feeds you.',
    weight: 0.5,
    value: 10.0,
    consumable: false,
    tags: ['tools_utility'],
  },
  flint_steel: {
    id: 'flint_steel',
    name: 'Flint & Steel',
    category: ItemCategory.TOOL,
    rarity: Rarity.COMMON,
    description: 'A wedge of flint and a struck steel, worn concave. Fire, given patience and dry tinder.',
    weight: 0.2,
    value: 4.0,
    consumable: false,
    tags: ['tools_utility'],
  },
  grappling_hook: {
    id: 'grappling_hook',
    name: 'Grappling Hook',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'Three barbs forge-welded to a ring. It will hold a man, once, and you find out which time is the last.',
    weight: 1.0,
    value: 15.0,
    consumable: false,
    tags: ['tools_utility'],
  },
  hoe: {
    id: 'hoe',
    name: 'Farmer\'s Hoe',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'Worn to a shine at the shoulders. Turns earth, and has settled arguments.',
    weight: 1.5,
    value: 5.0,
    consumable: false,
    durability: 60,
    tags: ['tools_utility'],
  },
  knife: {
    id: 'knife',
    name: 'Utility Knife',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'A working knife with a worn handle. Skins, cuts cord, eats. Not a weapon, but it has been.',
    weight: 0.3,
    value: 5.0,
    consumable: false,
    durability: 80,
    tags: ['tools_utility'],
  },
  lantern: {
    id: 'lantern',
    name: 'Oil Lantern',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'Shuttered horn and oil. The best light a walking man can carry.',
    weight: 1.0,
    value: 20.0,
    consumable: false,
    durability: 50,
    lightRadius: 5.0,
    burnHours: 12.0,
    tags: ['light_sources', 'tools_utility'],
  },
  lockpick: {
    id: 'lockpick',
    name: 'Lockpick Set',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'A wrap of picks and a tension bar, all of them hand-filed. Owning these is itself a crime.',
    weight: 0.2,
    value: 20.0,
    consumable: false,
    durability: 5,
    tags: ['tools_utility'],
  },
  mortar_pestle: {
    id: 'mortar_pestle',
    name: 'Mortar & Pestle',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'Stone, stained green in the bowl by whatever was ground in it last.',
    weight: 0.8,
    value: 12.0,
    consumable: false,
    tags: ['tools_utility'],
  },
  pickaxe: {
    id: 'pickaxe',
    name: 'Miner\'s Pickaxe',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'A miner’s tool with a hardened point. It goes through most things, given a swing.',
    weight: 3.0,
    value: 20.0,
    consumable: false,
    durability: 100,
    tags: ['tools_utility'],
  },
  rope: {
    id: 'rope',
    name: 'Coil of Rope',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'Hemp, forty feet, laid and whipped at both ends. There is no such thing as too much rope.',
    weight: 1.5,
    value: 8.0,
    consumable: false,
    tags: ['tools_utility'],
  },
  sewing_kit: {
    id: 'sewing_kit',
    name: 'Sewing Kit',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'Needles, thread, a scrap of leather for patches. The difference between a coat and a rag.',
    weight: 0.3,
    value: 10.0,
    consumable: false,
    durability: 10,
    tags: ['tools_utility'],
  },
  shovel: {
    id: 'shovel',
    name: 'Wooden Shovel',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'Iron-shod blade on an ash haft. Digs, buries, and at a pinch swings.',
    weight: 2.0,
    value: 8.0,
    consumable: false,
    durability: 80,
    tags: ['tools_utility'],
  },
  tinderbox: {
    id: 'tinderbox',
    name: 'Tinderbox',
    category: ItemCategory.TOOL,
    rarity: Rarity.UNCOMMON,
    description: 'Char cloth, flint and steel in a tin that shuts tight. Dry tinder is worth more than gold in the wet.',
    weight: 0.3,
    value: 5.0,
    consumable: false,
    tags: ['tools_utility'],
  },
  ancient_coin: {
    id: 'ancient_coin',
    name: 'Ancient Coin',
    category: ItemCategory.VALUABLE,
    rarity: Rarity.RARE,
    description: 'Older than the Church, by the look of the face on it. Thin as a fingernail, green with age.',
    weight: 0.1,
    value: 50.0,
    consumable: false,
    tags: ['valuables_currency'],
  },
  copper_coins: {
    id: 'copper_coins',
    name: 'Copper Coins (10)',
    category: ItemCategory.VALUABLE,
    rarity: Rarity.UNCOMMON,
    description: 'Thin copper, clipped at the edges. What most things actually cost.',
    weight: 0.1,
    value: 10.0,
    consumable: false,
    tags: ['valuables_currency'],
  },
  dye_plant: {
    id: 'dye_plant',
    name: 'Woad Plant',
    category: ItemCategory.VALUABLE,
    rarity: Rarity.UNCOMMON,
    description: 'Woad, cut and bundled. Blue, eventually, and a great deal of work in between.',
    weight: 0.2,
    value: 8.0,
    consumable: false,
    tags: ['valuables_currency'],
  },
  gemstone: {
    id: 'gemstone',
    name: 'Uncut Gemstone',
    category: ItemCategory.VALUABLE,
    rarity: Rarity.RARE,
    description: 'Rough, cloudy, and clearly worth something to somebody who cuts stones.',
    weight: 0.1,
    value: 80.0,
    consumable: false,
    tags: ['valuables_currency'],
  },
  gold_coins: {
    id: 'gold_coins',
    name: 'Gold Coins (10)',
    category: ItemCategory.VALUABLE,
    rarity: Rarity.ARTIFACT,
    description: 'Gold. Out here it is worth exactly what someone will trade for it, which is often nothing.',
    weight: 0.1,
    value: 100.0,
    consumable: false,
    tags: ['valuables_currency'],
  },
  gold_ring: {
    id: 'gold_ring',
    name: 'Gold Ring',
    category: ItemCategory.VALUABLE,
    rarity: Rarity.RARE,
    description: 'Plain gold, worn thin on one side. Somebody wore this for forty years.',
    weight: 0.1,
    value: 70.0,
    consumable: false,
    tags: ['valuables_currency'],
  },
  silver_coins: {
    id: 'silver_coins',
    name: 'Silver Coins (10)',
    category: ItemCategory.VALUABLE,
    rarity: Rarity.RARE,
    description: 'Silver, and enough of it to be noticed carrying.',
    weight: 0.1,
    value: 50.0,
    consumable: false,
    tags: ['valuables_currency'],
  },
  silver_necklace: {
    id: 'silver_necklace',
    name: 'Silver Necklace',
    category: ItemCategory.VALUABLE,
    rarity: Rarity.RARE,
    description: 'Fine links and a small clasp, tarnished dark. Too good for anybody out here.',
    weight: 0.2,
    value: 40.0,
    consumable: false,
    tags: ['valuables_currency'],
  },
  silver_ring: {
    id: 'silver_ring',
    name: 'Silver Ring',
    category: ItemCategory.VALUABLE,
    rarity: Rarity.RARE,
    description: 'Silver, with an inscription inside that has worn to nothing.',
    weight: 0.1,
    value: 25.0,
    consumable: false,
    tags: ['valuables_currency'],
  },
  spices: {
    id: 'spices',
    name: 'Pouch of Spices',
    category: ItemCategory.VALUABLE,
    rarity: Rarity.RARE,
    description: 'Pepper and something warmer, in a folded cloth. Worth more by weight than the man carrying it.',
    weight: 0.3,
    value: 35.0,
    consumable: false,
    tags: ['valuables_currency'],
  },
  trade_goods: {
    id: 'trade_goods',
    name: 'Bundle of Trade Goods',
    category: ItemCategory.VALUABLE,
    rarity: Rarity.RARE,
    description: 'Odds bundled for barter: cord, buttons, a little salt, a knife blade with no handle.',
    weight: 2.0,
    value: 25.0,
    consumable: false,
    tags: ['valuables_currency'],
  },
  blacksmith_hammer: {
    id: 'blacksmith_hammer',
    name: 'Blacksmith\'s Hammer',
    category: ItemCategory.WEAPON_BLUNT,
    rarity: Rarity.UNCOMMON,
    description: 'Dead weight on a long haft. Armour does not stop a blow like this, it only spreads it.',
    weight: 2.0,
    value: 18.0,
    consumable: false,
    damage: 10.2,
    sourceDice: '1d8',
    durability: 120,
    tags: ['blunt_weapons'],
  },
  hammer: {
    id: 'hammer',
    name: 'Carpenter\'s Hammer',
    category: ItemCategory.WEAPON_BLUNT,
    rarity: Rarity.UNCOMMON,
    description: 'A joiner’s hammer, heavy in the head. Meant for pegs, and it does not mind.',
    weight: 1.0,
    value: 8.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d6',
    durability: 100,
    tags: ['blunt_weapons', 'tools_utility'],
  },
  mace: {
    id: 'mace',
    name: 'Flanged Mace',
    category: ItemCategory.WEAPON_BLUNT,
    rarity: Rarity.RARE,
    description: 'Flanged iron on a haft. Made specifically for people wearing armour.',
    weight: 2.5,
    value: 40.0,
    consumable: false,
    damage: 10.2,
    sourceDice: '1d8',
    durability: 120,
    tags: ['blunt_weapons'],
  },
  quarterstaff: {
    id: 'quarterstaff',
    name: 'Quarterstaff',
    category: ItemCategory.WEAPON_BLUNT,
    rarity: Rarity.COMMON,
    description: 'A staff the height of a man. Keeps things further off than a blade does.',
    weight: 1.5,
    value: 4.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d6',
    durability: 80,
    tags: ['blunt_weapons'],
  },
  sledgehammer: {
    id: 'sledgehammer',
    name: 'Sledgehammer',
    category: ItemCategory.WEAPON_BLUNT,
    rarity: Rarity.RARE,
    description: 'Two-handed and enormously slow. If it connects, once is enough.',
    weight: 4.5,
    value: 25.0,
    consumable: false,
    damage: 14.2,
    sourceDice: '2d6',
    durability: 100,
    tags: ['blunt_weapons'],
  },
  stone_hatchet: {
    id: 'stone_hatchet',
    name: 'Stone Hatchet',
    category: ItemCategory.WEAPON_BLUNT,
    rarity: Rarity.COMMON,
    description: 'A knapped head lashed to a haft. It will take a limb off a tree, or come apart trying.',
    weight: 1.2,
    value: 4.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d6',
    durability: 30,
    tags: ['blunt_weapons'],
  },
  walking_stick: {
    id: 'walking_stick',
    name: 'Walking Stick',
    category: ItemCategory.WEAPON_BLUNT,
    rarity: Rarity.COMMON,
    description: 'Takes weight off the road, and settles arguments at a distance.',
    weight: 0.8,
    value: 2.0,
    consumable: false,
    damage: 7.0,
    sourceDice: '1d4',
    durability: 60,
    tags: ['blunt_weapons'],
  },
  warhammer: {
    id: 'warhammer',
    name: 'Warhammer',
    category: ItemCategory.WEAPON_BLUNT,
    rarity: Rarity.RARE,
    description: 'Military iron. It does not cut through mail; it caves in what is underneath.',
    weight: 3.0,
    value: 60.0,
    consumable: false,
    damage: 11.8,
    sourceDice: '1d10',
    durability: 130,
    tags: ['blunt_weapons'],
  },
  wooden_club: {
    id: 'wooden_club',
    name: 'Wooden Club',
    category: ItemCategory.WEAPON_BLUNT,
    rarity: Rarity.COMMON,
    description: 'A shaped length of hardwood. Crude, and entirely sufficient.',
    weight: 1.2,
    value: 2.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d6',
    durability: 40,
    tags: ['blunt_weapons'],
  },
  butcher_knife: {
    id: 'butcher_knife',
    name: 'Butcher\'s Knife',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.UNCOMMON,
    description: 'A heavy blade meant for carcasses. It does not much care whose.',
    weight: 0.5,
    value: 12.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d6',
    durability: 70,
    tags: ['edged_weapons'],
  },
  hunting_knife: {
    id: 'hunting_knife',
    name: 'Hunting Knife',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.UNCOMMON,
    description: 'Made for skinning, and it does that better than it fights. It still fights.',
    weight: 0.4,
    value: 15.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d4+1',
    durability: 90,
    tags: ['edged_weapons'],
  },
  iron_knife: {
    id: 'iron_knife',
    name: 'Iron Knife',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.UNCOMMON,
    description: 'A simple iron blade, well worn and serviceable. Worth more than it looks out here.',
    weight: 0.3,
    value: 10.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d4+1',
    durability: 80,
    tags: ['edged_weapons'],
  },
  long_sword: {
    id: 'long_sword',
    name: 'Long Sword',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.RARE,
    description: 'A soldier\'s weapon. Carrying it openly invites questions from the Iron Chain.',
    weight: 2.5,
    value: 50.0,
    consumable: false,
    damage: 10.2,
    sourceDice: '1d8',
    durability: 100,
    tags: ['edged_weapons'],
  },
  pitchfork: {
    id: 'pitchfork',
    name: 'Pitchfork',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.UNCOMMON,
    description: 'Three tines and a long haft. The commonest weapon in the Thornmarch, by a wide margin.',
    weight: 2.0,
    value: 8.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d6',
    durability: 60,
    tags: ['edged_weapons'],
  },
  rusty_knife: {
    id: 'rusty_knife',
    name: 'Rusty Knife',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.COMMON,
    description: 'Rust in the blade and rust in the tang. Whatever it cuts goes bad afterwards.',
    weight: 0.3,
    value: 3.0,
    consumable: false,
    damage: 7.0,
    sourceDice: '1d4',
    durability: 30,
    tags: ['edged_weapons'],
  },
  scythe: {
    id: 'scythe',
    name: 'Scythe',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.UNCOMMON,
    description: 'Two-handed and awkward, and everyone who sees it thinks the same thing.',
    weight: 2.5,
    value: 18.0,
    consumable: false,
    damage: 10.2,
    sourceDice: '1d8',
    durability: 50,
    tags: ['edged_weapons'],
  },
  sharp_dagger: {
    id: 'sharp_dagger',
    name: 'Sharp Dagger',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.UNCOMMON,
    description: 'Thin, fast, and easy to keep out of sight. It will snap if you put your weight behind it.',
    weight: 0.4,
    value: 20.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d6',
    durability: 70,
    tags: ['edged_weapons'],
  },
  short_sword: {
    id: 'short_sword',
    name: 'Short Sword',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.RARE,
    description: 'An arming sword, unremarkable, kept sharp by someone who is no longer using it.',
    weight: 1.5,
    value: 35.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d6',
    durability: 100,
    tags: ['edged_weapons'],
  },
  sickle: {
    id: 'sickle',
    name: 'Farmer\'s Sickle',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.UNCOMMON,
    description: 'For grain, before the fields went over. The curve still works on other things.',
    weight: 0.8,
    value: 6.0,
    consumable: false,
    damage: 7.0,
    sourceDice: '1d4',
    durability: 60,
    tags: ['edged_weapons', 'tools_utility'],
  },
  stone_knife: {
    id: 'stone_knife',
    name: 'Stone Knife',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.COMMON,
    description: 'A flake of stone lashed to a handle. It will open a throat once, maybe twice.',
    weight: 0.2,
    value: 2.0,
    consumable: false,
    damage: 6.2,
    sourceDice: '1d3',
    durability: 20,
    tags: ['edged_weapons'],
  },
  throwing_knife: {
    id: 'throwing_knife',
    name: 'Throwing Knife',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.UNCOMMON,
    description: 'Balanced for the throw. You will spend as long finding it again as you did throwing it.',
    weight: 0.3,
    value: 8.0,
    consumable: false,
    damage: 7.0,
    sourceDice: '1d4',
    durability: 50,
    tags: ['edged_weapons'],
  },
  wood_axe: {
    id: 'wood_axe',
    name: 'Woodcutter\'s Axe',
    category: ItemCategory.WEAPON_EDGED,
    rarity: Rarity.UNCOMMON,
    description: 'For timber. Splits other things without complaint.',
    weight: 2.0,
    value: 15.0,
    consumable: false,
    damage: 10.2,
    sourceDice: '1d8',
    durability: 90,
    tags: ['edged_weapons', 'tools_utility'],
  },
  crossbow: {
    id: 'crossbow',
    name: 'Crossbow',
    category: ItemCategory.WEAPON_RANGED,
    rarity: Rarity.RARE,
    description: 'A goat\u2019s-foot lever and a steel prod. Slow to span, and it does not care what you are wearing.',
    weight: 3.5,
    value: 80.0,
    consumable: false,
    damage: 11.8,
    sourceDice: '1d10',
    durability: 120,
    tags: ['ranged_weapons'],
  },
  hunting_bow: {
    id: 'hunting_bow',
    name: 'Hunting Bow',
    category: ItemCategory.WEAPON_RANGED,
    rarity: Rarity.RARE,
    description: 'A working bow, drawn smooth by long use. Made for deer and perfectly happy with worse.',
    weight: 1.5,
    value: 30.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d6',
    durability: 100,
    tags: ['ranged_weapons'],
  },
  javelin: {
    id: 'javelin',
    name: 'Hunting Javelin',
    category: ItemCategory.WEAPON_RANGED,
    rarity: Rarity.UNCOMMON,
    description: 'Fire-hardened point on a light shaft. Thrown, and then gone, unless you go and get it.',
    weight: 1.5,
    value: 12.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d6',
    durability: 60,
    tags: ['ranged_weapons'],
  },
  short_bow: {
    id: 'short_bow',
    name: 'Short Bow',
    category: ItemCategory.WEAPON_RANGED,
    rarity: Rarity.UNCOMMON,
    description: 'Short in the limb, quick to draw, and honest about its range.',
    weight: 1.0,
    value: 20.0,
    consumable: false,
    damage: 8.6,
    sourceDice: '1d6',
    durability: 80,
    tags: ['ranged_weapons'],
  },
  sling: {
    id: 'sling',
    name: 'Leather Sling',
    category: ItemCategory.WEAPON_RANGED,
    rarity: Rarity.UNCOMMON,
    description: 'A leather cradle and two cords. Older than swords, and it still kills.',
    weight: 0.3,
    value: 5.0,
    consumable: false,
    damage: 7.0,
    sourceDice: '1d4',
    durability: 60,
    tags: ['ranged_weapons'],
  },
  throwing_stones: {
    id: 'throwing_stones',
    name: 'Bag of Stones',
    category: ItemCategory.WEAPON_RANGED,
    rarity: Rarity.COMMON,
    description: 'River pebbles, chosen for weight and roundness. The ammunition the ground gives you free.',
    weight: 0.5,
    value: 1.0,
    consumable: false,
    damage: 6.2,
    sourceDice: '1d3',
    durability: 30,
    tags: ['ranged_weapons'],
  },
};
