/* ============================================================================
 * FIREBASE CONFIG
 *
 * These values are public by design — Firebase web configs are identifiers,
 * not secrets, and are visible in the page source of every Firebase site.
 * What protects the data is the Realtime Database rules, NOT this file.
 *
 * The rules this project expects are generated by src/leaderboard.js
 * (LEADERBOARD_RULES). They make the leaderboard append-only: entries can be
 * created but never edited or deleted, and the `players` node itself is not
 * writable, so no single call can wipe the board. Run
 *     window.LEADERBOARD.LEADERBOARD_RULES
 * in the console to print the JSON to paste into
 * Firebase Console -> Realtime Database -> Rules.
 * ========================================================================== */
window.FIREBASE_CONFIG = {
  apiKey: "AIzaSyCeW3uHXfO2ncGy2hjJnIYuxEP_EIN1Fug",
  authDomain: "goals-leaderboard.firebaseapp.com",
  databaseURL: "https://goals-leaderboard-default-rtdb.firebaseio.com",
  projectId: "goals-leaderboard",
  storageBucket: "goals-leaderboard.firebasestorage.app",
  messagingSenderId: "909173853183",
  appId: "1:909173853183:web:6d202418c97b87a42ff5ca",
};
