/* ============================================================================
 * FOOTBALL MANAGER — REAL SQUADS, THE REST OF THE WORLD
 *
 * The Premier League gets a full real squad from ../src/data.js. Every other
 * league in the game was entirely procedural until now — a Bayern Munich or a
 * Real Madrid built from the same random-name generator as a League Two side.
 *
 * This is the same idea at a smaller scale: real names, ages (where known) and
 * positions for 63 clubs across the Bundesliga, La Liga, Serie A, the Saudi Pro
 * League and MLS, sourced from public squad listings. There are no attribute
 * ratings behind these names — unlike the Premier League database, which ships
 * full 0-99 attributes for every player — so a squad is still built procedurally
 * to the club's level (generateSquad in world.js) and these names are grafted
 * onto it position by position, best generated player first. The result is a
 * club that plays with real personnel at a strength appropriate to its level,
 * not a second real-attribute database.
 *
 * Ages are the source's own listing at parse time and go stale over real
 * seasons; unlisted ages (`-` in the source) are left for the procedural age to
 * stand. Positions given only generically ("Defender", "Midfielder", "Forward",
 * or missing entirely) were resolved once, deterministically, to one of this
 * game's eight position keys — see manager/README.md.
 * ========================================================================== */
(function (root) {
  "use strict";
  const MG = (root.MG = root.MG || {});

  const REAL_SQUADS_INTL = {
    "AC Milan": [
      { name: "Koni De Winter", pos: "CB" },
      { name: "Lorenzo Torriani", pos: "GK" },
      { name: "Mike Maignan", pos: "GK" },
      { name: "Pietro Terracciano", pos: "GK" },
      { name: "Samuele Ricci", pos: "CM" },
    ],
    "Al Ahli": [
      { name: "Abdullah Otayf", pos: "DM", age: 33 },
      { name: "Abdulrahman Al-Sanbi", pos: "DM", age: 25 },
      { name: "Enzo Millot", pos: "AM", age: 23 },
      { name: "Firas Al-Buraikan", pos: "FW" },
      { name: "Ivan Toney", pos: "FW" },
      { name: "Riyad Mahrez", pos: "WG" },
      { name: "Roger Ibañez", pos: "CB" },
      { name: "Zakaria Hawsawi", pos: "DM", age: 25 },
      { name: "Ziyad Al-Johani", pos: "FW" },
    ],
    "Al Akhdoud": [
      { name: "Gökhan Gül", pos: "DM", age: 27 },
      { name: "Juan Pedroza", pos: "CM", age: 26 },
      { name: "Samuel Portugal", pos: "GK", age: 31 },
    ],
    "Al Ettifaq": [
      { name: "Abdullah Khateeb", pos: "FB", age: 30 },
      { name: "Francisco Calvo", pos: "CB" },
      { name: "Georginio Wijnaldum", pos: "DM" },
      { name: "Jack Hendry", pos: "CB" },
      { name: "Khalid Al-Ghannam", pos: "CM" },
      { name: "Marek Rodák", pos: "GK", age: 28 },
      { name: "Ondrej Duda", pos: "CM", age: 30 },
    ],
    "Al Fateh": [
      { name: "Fernando Pacheco", pos: "GK", age: 33 },
      { name: "Jorge Fernandes", pos: "FB", age: 28 },
      { name: "Marwane Saâdane", pos: "FB" },
      { name: "Saeed Ba Atiyah", pos: "DM", age: 31 },
      { name: "Ziyad Al-Jari", pos: "CB", age: 23 },
    ],
    "Al Hilal": [
      { name: "Ali Lajami", pos: "CB" },
      { name: "Crysencio Summerville", pos: "FW" },
      { name: "Kalidou Koulibaly", pos: "CB" },
      { name: "Karim Benzema", pos: "WG" },
      { name: "Malcom", pos: "FW" },
      { name: "Mohammed Kanno", pos: "AM" },
      { name: "Mohammed Mahzari", pos: "CB" },
      { name: "Moteb Al-Harbi", pos: "FB" },
      { name: "Rúben Neves", pos: "CM" },
      { name: "Sergej Milinković-Savić", pos: "DM" },
      { name: "Yassine Bounou", pos: "GK" },
    ],
    "Al Ittihad": [
      { name: "Ahmed Sharahili", pos: "CB" },
      { name: "Hamed Al-Shanqiti", pos: "WG" },
      { name: "Hassan Kadesh", pos: "CB", age: 32 },
      { name: "Karim Benzema", pos: "WG", age: 37 },
      { name: "Mohammed Al-Absi", pos: "CB" },
      { name: "Muhannad Shenqeeti", pos: "DM", age: 26 },
      { name: "Predrag Rajković", pos: "GK", age: 29 },
      { name: "Roger Fernandes", pos: "CM" },
      { name: "Youssef En-Nesyri", pos: "WG", age: 28 },
    ],
    "Al Khaleej": [
      { name: "Anthony Moris", pos: "GK", age: 35 },
      { name: "Giorgos Masouras", pos: "CM" },
      { name: "Mohammed Al-Khabrani", pos: "CB", age: 31 },
      { name: "Paolo Fernandes", pos: "AM", age: 26 },
      { name: "Pedro Rebocho", pos: "CB", age: 30 },
    ],
    "Al Nassr": [
      { name: "Cristiano Ronaldo", pos: "FW", age: 41 },
      { name: "João Félix", pos: "WG" },
      { name: "Kingsley Coman", pos: "FW" },
      { name: "Sadio Mané", pos: "FW", age: 34 },
    ],
    "Al Qadsiah": [
      { name: "Julián Quiñones", pos: "FW" },
      { name: "Mateo Retegui", pos: "CB" },
      { name: "Meshary Sanyor", pos: "GK", age: 24 },
    ],
    "Al Raed": [
      { name: "Juanjo Narváez", pos: "FB" },
      { name: "Oumar Gonzalez", pos: "CB" },
      { name: "Yousri Bouzok", pos: "FW" },
    ],
    "Al Shabab": [
      { name: "Abderrazak Hamdallah", pos: "FW" },
      { name: "Marcelo Grohe", pos: "GK", age: 39 },
      { name: "Wesley Hoedt", pos: "CB", age: 32 },
      { name: "Yannick Carrasco", pos: "WG" },
    ],
    "Al Taawoun": [
      { name: "Andrei Girotto", pos: "CB" },
      { name: "Aschraf El Mahdioui", pos: "CM", age: 29 },
      { name: "Mailson", pos: "GK", age: 28 },
      { name: "Mohammed Mahzari", pos: "CB", age: 23 },
      { name: "Roger Martínez", pos: "WG", age: 31 },
    ],
    "Atalanta": [
      { name: "Albert Navarro", pos: "CB", age: 19 },
      { name: "Charles De Ketelaere", pos: "FW", age: 25 },
      { name: "Davide Zappacosta", pos: "CB", age: 33 },
      { name: "Éderson", pos: "CM", age: 26 },
      { name: "Francesco Rossi", pos: "GK", age: 35 },
      { name: "Giacomo Raspadori", pos: "WG", age: 26 },
      { name: "Gianluca Scamacca", pos: "WG", age: 27 },
      { name: "Giorgio Scalvini", pos: "CB", age: 22 },
      { name: "Kamaldeen Sulemana", pos: "FW" },
      { name: "Marco Carnesecchi", pos: "GK", age: 25 },
      { name: "Marco Sportiello", pos: "GK", age: 34 },
      { name: "Mario Pasalic", pos: "AM", age: 31 },
      { name: "Nikola Krstovic", pos: "FW", age: 26 },
      { name: "Piotr Pardel", pos: "GK", age: 21 },
    ],
    "Atlanta United": [
      { name: "Brad Guzan", pos: "GK", age: 40 },
      { name: "Josh Cohen", pos: "GK", age: 32 },
      { name: "Jayden Hibbert", pos: "GK", age: 20 },
      { name: "Luis Abram", pos: "CB", age: 29 },
      { name: "Pedro Amador", pos: "CB", age: 26 },
      { name: "Juan Berrocal", pos: "CB", age: 25 },
      { name: "Dominik Chong Qui", pos: "FB" },
      { name: "Noah Cobb", pos: "CB", age: 20 },
      { name: "Matthew Edwards", pos: "FB" },
      { name: "Stian Gregersen", pos: "CB", age: 29 },
      { name: "Ronald Hernández", pos: "FB", age: 27 },
      { name: "Brooks Lennon", pos: "FB", age: 27 },
      { name: "Enea Mihaj", pos: "FB", age: 26 },
      { name: "Efraín Morales", pos: "CB", age: 20 },
      { name: "Derrick Williams", pos: "CB", age: 32 },
      { name: "Ajani Fortune", pos: "DM", age: 22 },
      { name: "Edwin Mosquera", pos: "WG", age: 24 },
      { name: "Rodrigo Neri", pos: "FW" },
      { name: "Jamal Thiaré", pos: "WG" },
      { name: "Patrick Weah", pos: "FW" },
    ],
    "Atletico Madrid": [
      { name: "Ademola Lookman", pos: "AM", age: 28 },
      { name: "Álex Baena", pos: "AM", age: 24 },
      { name: "Alexander Sørloth", pos: "FW", age: 30 },
      { name: "Álvaro Moreno", pos: "GK", age: 20 },
      { name: "Antoine Griezmann", pos: "WG", age: 35 },
      { name: "Giuliano Simeone", pos: "FW", age: 23 },
      { name: "Jan Oblak", pos: "GK", age: 33 },
      { name: "Juan Musso", pos: "GK", age: 32 },
      { name: "Julián Álvarez", pos: "FW", age: 26 },
      { name: "Koke", pos: "CM", age: 34 },
      { name: "Mario de Luis", pos: "GK", age: 24 },
      { name: "Nico González", pos: "WG", age: 28 },
      { name: "Salvi Esquivel", pos: "GK", age: 20 },
      { name: "Thiago Almada", pos: "AM", age: 25 },
    ],
    "Augsburg": [
      { name: "Alexis Claude-Maurice", pos: "FB" },
      { name: "Anton Kade", pos: "DM" },
      { name: "Daniel Klein", pos: "GK" },
      { name: "Dimitris Giannoulis", pos: "CB" },
      { name: "Fabian Rieder", pos: "FW" },
      { name: "Han-Noah Massengo", pos: "CM" },
      { name: "Michael Gregoritsch", pos: "WG" },
      { name: "Robin Fellhauer", pos: "CM" },
    ],
    "Austin FC": [
      { name: "Damian Las", pos: "GK", age: 22 },
      { name: "Brad Stuver", pos: "GK", age: 33 },
      { name: "Jon Bell", pos: "CB", age: 27 },
      { name: "Guilherme Biro", pos: "FB", age: 24 },
      { name: "Julio Cascante", pos: "CB", age: 31 },
      { name: "Mikkel Desler", pos: "FB", age: 30 },
      { name: "Mateja Djordjević", pos: "CB" },
      { name: "Jon Gallagher", pos: "FB", age: 29 },
      { name: "Brendan Hines-Ike", pos: "FB", age: 30 },
      { name: "Žan Kolmanič", pos: "FB", age: 25 },
      { name: "Joseph Rosales", pos: "CB", age: 24 },
      { name: "Oleksandr Svatok", pos: "CB", age: 30 },
      { name: "Riley Thomas", pos: "FB", age: 24 },
      { name: "Leo Väisänen", pos: "CB", age: 27 },
      { name: "Micah Burton", pos: "CM" },
      { name: "Nico Dubersarsky", pos: "CM" },
      { name: "Dani Pereira", pos: "CM", age: 24 },
      { name: "Besard Sabovic", pos: "DM" },
      { name: "Ilie Sánchez", pos: "CM", age: 34 },
      { name: "Ervin Torres", pos: "CM" },
      { name: "Owen Wolff", pos: "DM", age: 20 },
      { name: "Jáder Obrian", pos: "WG", age: 29 },
      { name: "Diego Rubio", pos: "FW", age: 31 },
      { name: "Robert Taylor", pos: "WG", age: 30 },
      { name: "Myrto Uzuni", pos: "WG", age: 29 },
      { name: "Brandon Vazquez", pos: "FW", age: 26 },
    ],
    "Barcelona": [
      { name: "Dani Olmo", pos: "CM", age: 28 },
      { name: "Diego Kochen", pos: "GK", age: 20 },
      { name: "Eder Aller", pos: "GK", age: 19 },
      { name: "Eric García", pos: "CB", age: 25 },
      { name: "Fermín López", pos: "CM", age: 23 },
      { name: "Ferran Torres", pos: "FW", age: 26 },
      { name: "Frenkie de Jong", pos: "AM" },
      { name: "João Cancelo", pos: "CB", age: 32 },
      { name: "Lamine Yamal", pos: "FW", age: 18 },
      { name: "Marc Bernal", pos: "CM", age: 19 },
      { name: "Marcus Rashford", pos: "FW", age: 28 },
      { name: "Pedri", pos: "AM", age: 23 },
      { name: "Raphinha", pos: "FW", age: 29 },
      { name: "Robert Lewandowski", pos: "WG", age: 37 },
      { name: "Ronald Araújo", pos: "FB", age: 27 },
    ],
    "Bayer Leverkusen": [
      { name: "Alejandro Grimaldo", pos: "FB", age: 30 },
      { name: "Aleix García", pos: "DM", age: 29 },
      { name: "Christian Kofane", pos: "FW", age: 19 },
      { name: "Edmond Tapsoba", pos: "CB", age: 27 },
      { name: "Ernest Poku", pos: "WG", age: 22 },
      { name: "Ibrahim Maza", pos: "AM", age: 20 },
      { name: "Janis Blaswich", pos: "GK", age: 35 },
      { name: "Jarell Quansah", pos: "FB", age: 23 },
      { name: "Jesper Schlich", pos: "GK", age: 18 },
      { name: "Jonas Hofmann", pos: "AM", age: 33 },
      { name: "Jonas Omlin", pos: "GK", age: 32 },
      { name: "Malik Tillman", pos: "AM", age: 24 },
      { name: "Martin Terrier", pos: "WG", age: 29 },
      { name: "Patrik Schick", pos: "WG", age: 30 },
    ],
    "Bayern Munich": [
      { name: "Aleksandar Pavlovic", pos: "CM", age: 22 },
      { name: "Alexander Nübel", pos: "GK", age: 29 },
      { name: "Harry Kane", pos: "FW", age: 32 },
      { name: "Jamal Musiala", pos: "AM" },
      { name: "Jannis Bärtl", pos: "GK", age: 20 },
      { name: "Jonas Urbig", pos: "GK", age: 22 },
      { name: "Leon Goretzka", pos: "CM", age: 31 },
      { name: "Leon Klanac", pos: "GK", age: 19 },
      { name: "Leonard Prescott", pos: "GK", age: 16 },
      { name: "Lennart Karl", pos: "CM", age: 18 },
      { name: "Luis Díaz", pos: "WG", age: 29 },
      { name: "Michael Olise", pos: "DM", age: 24 },
      { name: "Nicolas Jackson", pos: "FW", age: 25 },
      { name: "Raphaël Guerreiro", pos: "FB", age: 32 },
      { name: "Serge Gnabry", pos: "FW", age: 30 },
    ],
    "Bologna": [
      { name: "Davide Baroncioni", pos: "DM" },
      { name: "Federico Ravaglia", pos: "GK", age: 26 },
      { name: "Łukasz Skorupski", pos: "GK", age: 35 },
      { name: "Massimo Pessina", pos: "AM" },
      { name: "Matteo Franceschelli", pos: "GK", age: 17 },
      { name: "Nicolò Casale", pos: "CB" },
      { name: "Riccardo Gnudi", pos: "GK", age: 17 },
    ],
    "Borussia Dortmund": [
      { name: "Aaron Anselmino", pos: "FB" },
      { name: "Alexander Meyer", pos: "GK" },
      { name: "Almugera Kabar", pos: "CB" },
      { name: "Daniel Svensson", pos: "CB" },
      { name: "Felix Nmecha", pos: "CM" },
      { name: "Filippo Mané", pos: "CB" },
      { name: "Gregor Kobel", pos: "GK", age: 27 },
      { name: "Guille Bueno", pos: "CB" },
      { name: "Julian Brandt", pos: "CM" },
      { name: "Julian Ryerson", pos: "CB" },
      { name: "Karim Adeyemi", pos: "WG" },
      { name: "Marcel Sabitzer", pos: "DM" },
      { name: "Niklas Süle", pos: "CB" },
      { name: "Nico Schlotterbeck", pos: "CB" },
      { name: "Patrick Drewes", pos: "GK" },
      { name: "Ramy Bensebaini", pos: "CB" },
      { name: "Silas Ostrzinski", pos: "GK" },
      { name: "Waldemar Anton", pos: "CB" },
      { name: "Yan Couto", pos: "FB" },
    ],
    "Cagliari": [
      { name: "Adam Obert", pos: "CB" },
      { name: "Alen Sherri", pos: "GK" },
      { name: "Alessandro Russo", pos: "AM" },
      { name: "Elia Caprile", pos: "GK", age: 23 },
      { name: "Giuseppe Ciocci", pos: "GK" },
      { name: "Ivan Sulev", pos: "CM" },
      { name: "Marco Palestra", pos: "DM", age: 20 },
      { name: "Nicola Grandu", pos: "FB" },
      { name: "Sebastiano Esposito", pos: "WG", age: 23 },
      { name: "Velizar-Ilia Svetozarov Iliev", pos: "GK" },
      { name: "Yael Trepy", pos: "CM" },
    ],
    "Charlotte FC": [
      { name: "David Bingham", pos: "GK", age: 35 },
      { name: "Drake Callender", pos: "GK", age: 27 },
      { name: "Kristijan Kahlina", pos: "GK", age: 32 },
      { name: "George Marks", pos: "GK", age: 25 },
      { name: "Nathan Byrne", pos: "FB", age: 33 },
      { name: "Baye Coulibaly", pos: "CB" },
      { name: "Hamady Diop", pos: "FB", age: 22 },
      { name: "Souleyman Doumbia", pos: "FB", age: 28 },
      { name: "Jahlane Forbes", pos: "FB" },
      { name: "Adilson Malanda", pos: "CB", age: 23 },
      { name: "Tim Ream", pos: "CB", age: 37 },
      { name: "Harry Toffolo", pos: "FB", age: 29 },
      { name: "Bill Tuiloma", pos: "CB", age: 29 },
      { name: "Ben Bender", pos: "CM", age: 24 },
      { name: "Pep Biel", pos: "AM", age: 28 },
      { name: "Brandt Bronico", pos: "CM", age: 29 },
      { name: "Djibril Diani", pos: "CM", age: 27 },
      { name: "Jack Neeley", pos: "AM" },
      { name: "Nick Scardina", pos: "CM" },
      { name: "Ashley Westwood", pos: "CM", age: 34 },
      { name: "Eryk Williamson", pos: "CM", age: 27 },
      { name: "Liel Abada", pos: "WG", age: 23 },
      { name: "Nimfasha Berchimas", pos: "WG" },
      { name: "Tyger Smalls", pos: "WG" },
      { name: "Karol Swiderski", pos: "WG", age: 28 },
      { name: "Wilfried Zaha", pos: "WG", age: 32 },
    ],
    "Chicago Fire": [
      { name: "Chris Brady", pos: "GK", age: 21 },
      { name: "Bryan Dowd", pos: "GK", age: 23 },
      { name: "Jeff Gal", pos: "GK", age: 32 },
      { name: "Leonardo Barroso", pos: "FB", age: 20 },
      { name: "Christopher Cupps", pos: "FB" },
      { name: "Jonathan Dean", pos: "CB", age: 27 },
      { name: "Jack Elliott", pos: "FB", age: 30 },
      { name: "Omar González", pos: "CB", age: 36 },
      { name: "Andrew Gutman", pos: "FB", age: 28 },
      { name: "Viktor Radojević", pos: "CB" },
      { name: "Justin Reynolds", pos: "CB" },
      { name: "Sam Rogers", pos: "CB", age: 25 },
      { name: "Joel Waterman", pos: "CB", age: 29 },
      { name: "Kellyn Acosta", pos: "AM", age: 29 },
      { name: "Jonathan Bamba", pos: "AM" },
      { name: "Dylan Borso", pos: "CM" },
      { name: "Dje D'Avilla", pos: "DM" },
      { name: "André Franco", pos: "CM", age: 26 },
      { name: "Brian Gutiérrez", pos: "CM", age: 21 },
      { name: "Maren Haile-Selassie", pos: "AM", age: 26 },
      { name: "Chris Mueller", pos: "DM", age: 28 },
      { name: "Sergio Oregel Jr.", pos: "DM" },
      { name: "Mauricio Pineda", pos: "CM", age: 27 },
      { name: "David Poreba", pos: "AM" },
      { name: "Sam Williams", pos: "AM" },
      { name: "Philip Zinckernagel", pos: "CM", age: 30 },
      { name: "Dean Boltz", pos: "FW" },
      { name: "Hugo Cuypers", pos: "WG", age: 28 },
      { name: "Omari Glasgow", pos: "FW" },
    ],
    "Colorado Rapids": [
      { name: "Adam Beaudry", pos: "GK" },
      { name: "Zack Campagnolo", pos: "GK" },
      { name: "Nicolas Hansen", pos: "GK" },
      { name: "Zack Steffen", pos: "GK", age: 29 },
      { name: "Paxten Aaronson", pos: "CM", age: 21 },
      { name: "Daouda Amadou", pos: "DM" },
      { name: "Josh Atencio", pos: "AM", age: 22 },
      { name: "Cole Bassett", pos: "CM", age: 23 },
      { name: "Kévin Cabral", pos: "FW", age: 25 },
      { name: "Reggie Cannon", pos: "CB", age: 26 },
      { name: "Ali Fadal", pos: "CM" },
      { name: "Wayne Frederick", pos: "CM" },
      { name: "Alex Harris", pos: "WG" },
      { name: "Rob Holding", pos: "CB", age: 29 },
      { name: "Bryce Jamison", pos: "CM" },
      { name: "Ted Ku-DiPietro", pos: "AM" },
      { name: "Oliver Larraz", pos: "AM" },
      { name: "Andreas Maxsø", pos: "CB", age: 30 },
      { name: "Rafael Navarro", pos: "FW" },
      { name: "Connor Ronan", pos: "CM", age: 27 },
      { name: "Keegan Rosenberry", pos: "CB", age: 31 },
      { name: "Rafael Santos", pos: "CB" },
      { name: "Jackson Travis", pos: "FB" },
      { name: "Sam Vines", pos: "FB", age: 25 },
      { name: "Darren Yapi", pos: "FW" },
    ],
    "Columbus Crew": [
      { name: "Evan Bush", pos: "GK", age: 39 },
      { name: "Patrick Schulte", pos: "GK", age: 23 },
      { name: "Malte Amundsen", pos: "FB", age: 26 },
      { name: "Rudy Camacho", pos: "CB", age: 34 },
      { name: "Andrés Herrera", pos: "FB", age: 26 },
      { name: "DeJuan Jones", pos: "FB", age: 27 },
      { name: "Steven Moreira", pos: "FB", age: 30 },
      { name: "Darlington Nagbe", pos: "CM", age: 34 },
      { name: "Diego Rossi", pos: "AM", age: 26 },
      { name: "Cucho Hernández", pos: "FW", age: 25 },
    ],
    "Como": [
      { name: "Adrian Lahdo", pos: "CM", age: 18 },
      { name: "Alberto Moreno", pos: "CB", age: 33 },
      { name: "Anastasios Douvikas", pos: "FW", age: 26 },
      { name: "Henrique Menke", pos: "GK", age: 19 },
      { name: "Jayden Addai", pos: "FW", age: 20 },
      { name: "Jean Butez", pos: "GK", age: 30 },
      { name: "Lucas Da Cunha", pos: "CM", age: 24 },
      { name: "Marc-Oliver Kempf", pos: "CB", age: 31 },
      { name: "Martin Baturina", pos: "CM", age: 23 },
      { name: "Mauro Vigorito", pos: "GK", age: 36 },
      { name: "Máximo Perrone", pos: "CM", age: 23 },
      { name: "Nico Paz", pos: "DM", age: 21 },
      { name: "Nikola Cavlina", pos: "GK", age: 23 },
      { name: "Noel Törnqvist", pos: "GK", age: 24 },
    ],
    "Damac": [
      { name: "Abdelkader Bedrane", pos: "FB", age: 34 },
      { name: "Jamal Harkass", pos: "FB", age: 30 },
      { name: "Valentín Vada", pos: "CM" },
    ],
    "Eintracht Frankfurt": [
      { name: "Amil Siljevic", pos: "GK", age: 19 },
      { name: "Arnaud Kalimuendo", pos: "FW", age: 24 },
      { name: "Arthur Theate", pos: "CB", age: 26 },
      { name: "Ayoube Amaimouni", pos: "WG", age: 21 },
      { name: "Can Uzun", pos: "AM", age: 20 },
      { name: "Farès Chaïbi", pos: "CM", age: 23 },
      { name: "Hugo Larsson", pos: "CM", age: 21 },
      { name: "Jean-Mattéo Bahoya", pos: "FW", age: 21 },
      { name: "Jonathan Burkardt", pos: "FW", age: 25 },
      { name: "Mahmoud Dahoud", pos: "AM", age: 30 },
      { name: "Nathaniel Brown", pos: "FB", age: 22 },
      { name: "Rasmus Kristensen", pos: "CB", age: 28 },
      { name: "Ritsu Doan", pos: "CM", age: 27 },
      { name: "Robin Koch", pos: "FB", age: 29 },
    ],
    "Espanyol": [
      { name: "Adama Timera", pos: "WG", age: 21 },
      { name: "Alex Almansa", pos: "FW", age: 22 },
      { name: "Ángel Fortuño", pos: "GK", age: 24 },
      { name: "Cala", pos: "FW", age: 26 },
      { name: "Enrique García", pos: "FW", age: 36 },
      { name: "Javier Puado", pos: "FW", age: 28 },
      { name: "Leandro Cabrera", pos: "FB", age: 35 },
      { name: "Llorenç Serred", pos: "GK", age: 20 },
      { name: "Marko Dmitrovic", pos: "GK", age: 34 },
      { name: "Pere Milla", pos: "CM", age: 33 },
      { name: "Pol Lozano", pos: "DM", age: 26 },
      { name: "Pol Tristan", pos: "GK", age: 24 },
      { name: "Roberto Fernández", pos: "FW", age: 24 },
      { name: "Tyrhys Dolan", pos: "FW", age: 24 },
    ],
    "FC Cincinnati": [
      { name: "Roman Celentano", pos: "GK", age: 25 },
      { name: "Alec Kann", pos: "GK", age: 35 },
      { name: "Evan Louro", pos: "GK", age: 29 },
      { name: "Paul Walters", pos: "GK", age: 21 },
      { name: "Álvaro Barreal", pos: "FB", age: 24 },
      { name: "Lukas Engel", pos: "FB" },
      { name: "Teenage Hadebe", pos: "CB", age: 29 },
      { name: "Nick Hagglund", pos: "FB", age: 32 },
      { name: "Matt Miazga", pos: "CB", age: 29 },
      { name: "Miles Robinson", pos: "CB", age: 27 },
      { name: "Brad Smith", pos: "CB", age: 30 },
      { name: "Tah Brian Anunga", pos: "CM", age: 28 },
      { name: "Pavel Bucha", pos: "DM", age: 27 },
      { name: "Ender Echenique", pos: "DM" },
      { name: "Evander", pos: "AM", age: 26 },
      { name: "Luca Orellano", pos: "CM", age: 24 },
      { name: "Corey Baird", pos: "FW", age: 29 },
      { name: "Brenner", pos: "FW", age: 25 },
      { name: "Kévin Denkey", pos: "FW", age: 24 },
      { name: "Ayoub Jabbari", pos: "WG" },
      { name: "Dominik Marczuk", pos: "WG" },
      { name: "Kenji Mboma Dem", pos: "WG" },
    ],
    "Fiorentina": [
      { name: "David de Gea", pos: "GK" },
      { name: "Luca Lezzerini", pos: "GK" },
      { name: "Mattia Magalotti", pos: "GK", age: 18 },
      { name: "Oliver Christensen", pos: "GK" },
      { name: "Pietro Leonardelli", pos: "GK" },
      { name: "Tariq Lamptey", pos: "CB", age: 25 },
      { name: "Tommaso Martinelli", pos: "GK" },
    ],
    "Freiburg": [
      { name: "Florian Müller", pos: "GK", age: 28 },
      { name: "Igor Matanovic", pos: "WG", age: 23 },
      { name: "Jannik Huth", pos: "GK", age: 32 },
      { name: "Johan Manzambi", pos: "DM", age: 20 },
      { name: "Lucas Höler", pos: "FW", age: 31 },
      { name: "Lukas Kübler", pos: "CB", age: 33 },
      { name: "Matthias Ginter", pos: "CB", age: 32 },
      { name: "Maximilian Eggestein", pos: "CM", age: 29 },
      { name: "Niklas Beste", pos: "CB", age: 27 },
      { name: "Noah Atubolu", pos: "GK", age: 23 },
      { name: "Patrick Osterhage", pos: "AM", age: 26 },
      { name: "Philipp Lienhart", pos: "FB", age: 29 },
      { name: "Philipp Treu", pos: "CB", age: 25 },
      { name: "Vincenzo Grifo", pos: "AM", age: 33 },
      { name: "Yuito Suzuki", pos: "DM", age: 24 },
    ],
    "Genoa": [
      { name: "Benjamin Siegrist", pos: "GK" },
      { name: "Daniele Sommariva", pos: "GK" },
      { name: "Ernestas Lysionok", pos: "GK" },
      { name: "Johan Vásquez", pos: "CB", age: 26 },
      { name: "Justin Bijlow", pos: "GK" },
      { name: "Lorenzo Colombo", pos: "FW", age: 23 },
      { name: "Mikael Ellertsson", pos: "AM", age: 23 },
      { name: "Morten Frendrup", pos: "CM", age: 24 },
      { name: "Nicola Leali", pos: "GK" },
      { name: "Rendijs Mihelsons", pos: "GK" },
    ],
    "Getafe": [
      { name: "Abdel Abqar", pos: "CB", age: 27 },
      { name: "Abu Kamara", pos: "FW", age: 22 },
      { name: "Adrián Liso", pos: "WG", age: 21 },
      { name: "Adrián Riquelme", pos: "CM", age: 20 },
      { name: "Borja Mayoral", pos: "WG", age: 29 },
      { name: "David Soria", pos: "GK", age: 33 },
      { name: "Diego Ferrer", pos: "GK", age: 19 },
      { name: "Jirí Letácek", pos: "GK", age: 27 },
      { name: "Jorge Benito", pos: "GK", age: 20 },
      { name: "Kiko Femenía", pos: "CB", age: 35 },
      { name: "Luis Vázquez", pos: "FW", age: 25 },
      { name: "Mario Martín", pos: "CM", age: 22 },
      { name: "Martín Satriano", pos: "FW", age: 25 },
      { name: "Mauro Arambarri", pos: "DM", age: 30 },
    ],
    "Girona": [
      { name: "Abel Ruiz", pos: "WG", age: 26 },
      { name: "Aleksandar Andreev", pos: "GK", age: 20 },
      { name: "Azzedine Ounahi", pos: "AM", age: 26 },
      { name: "Claudio Echeverri", pos: "CM", age: 20 },
      { name: "Cristhian Stuani", pos: "FW", age: 39 },
      { name: "Fran Beltrán", pos: "CM", age: 27 },
      { name: "Joel Roca", pos: "CM", age: 21 },
      { name: "Juan Carlos", pos: "GK", age: 38 },
      { name: "Marc-André ter Stegen", pos: "GK", age: 34 },
      { name: "Paulo Gazzaniga", pos: "GK", age: 34 },
      { name: "Rubén Blanco", pos: "GK", age: 30 },
      { name: "Thomas Lemar", pos: "DM", age: 30 },
      { name: "Vladyslav Krapyvtsov", pos: "GK", age: 20 },
      { name: "Vladyslav Vanat", pos: "WG", age: 24 },
    ],
    "Heidenheim": [
      { name: "Budu Zivzivadze", pos: "WG", age: 32 },
      { name: "Diant Ramaj", pos: "GK" },
      { name: "Frank Feller", pos: "GK" },
      { name: "Marvin Pieringer", pos: "FW" },
      { name: "Paul Tschernuth", pos: "GK" },
      { name: "Stefan Schimmer", pos: "FW" },
    ],
    "Hoffenheim": [
      { name: "Albian Hajdari", pos: "FB", age: 23 },
      { name: "Alexander Prass", pos: "FB", age: 25 },
      { name: "Andrej Kramaric", pos: "FW", age: 34 },
      { name: "Bazoumana Touré", pos: "WG", age: 20 },
      { name: "Fisnik Asllani", pos: "FW", age: 23 },
      { name: "Grischa Prömel", pos: "CM", age: 31 },
      { name: "Luis Engelns", pos: "CM", age: 19 },
      { name: "Luca Philipp", pos: "GK", age: 25 },
      { name: "Lúkas Petersson", pos: "GK", age: 22 },
      { name: "Max Moerstedt", pos: "FW", age: 20 },
      { name: "Ozan Kabak", pos: "CB", age: 26 },
      { name: "Robin Hranác", pos: "CB", age: 26 },
      { name: "Tim Lemperle", pos: "WG", age: 24 },
      { name: "Wouter Burger", pos: "DM", age: 25 },
    ],
    "Houston Dynamo": [
      { name: "Jimmy Maurer", pos: "GK", age: 36 },
      { name: "Stephen Annor Gyamfi", pos: "FW", age: 21 },
      { name: "Sebastián Rodríguez", pos: "CM", age: 17 },
      { name: "Júnior Urso", pos: "CM", age: 36 },
    ],
    "Inter Milan": [
      { name: "Alain Taho", pos: "GK", age: 19 },
      { name: "Alessandro Calligaris", pos: "GK", age: 21 },
      { name: "Ange-Yoan Bonny", pos: "FW", age: 22 },
      { name: "Carlos Augusto", pos: "CB", age: 27 },
      { name: "Denzel Dumfries", pos: "CB", age: 30 },
      { name: "Federico Dimarco", pos: "CB", age: 28 },
      { name: "Hakan Çalhanoglu", pos: "DM", age: 32 },
      { name: "Henrikh Mkhitaryan", pos: "CM", age: 37 },
      { name: "Kristjan Asllani", pos: "AM", age: 24 },
      { name: "Lautaro Martínez", pos: "FW", age: 28 },
      { name: "Luis Henrique", pos: "WG", age: 24 },
      { name: "Manuel Akanji", pos: "CB", age: 30 },
      { name: "Marcus Thuram", pos: "FW", age: 28 },
      { name: "Pio Esposito", pos: "WG", age: 21 },
    ],
    "Juventus": [
      { name: "Bremer", pos: "FB", age: 29 },
      { name: "Carlo Pinsoglio", pos: "GK", age: 36 },
      { name: "Dusan Vlahovic", pos: "WG", age: 26 },
      { name: "Jonathan David", pos: "FW", age: 26 },
      { name: "Kenan Yildiz", pos: "FW", age: 21 },
      { name: "Matteo Fuscaldo", pos: "GK", age: 21 },
      { name: "Mattia Perin", pos: "GK", age: 33 },
      { name: "Michele Di Gregorio", pos: "GK", age: 28 },
      { name: "Raffaele Huli", pos: "GK", age: 17 },
      { name: "Riccardo Radu", pos: "GK", age: 18 },
      { name: "Simone Scaglia", pos: "GK", age: 21 },
      { name: "Stefano Mangiapoco", pos: "GK", age: 22 },
      { name: "Timothy Weah", pos: "WG", age: 26 },
      { name: "Weston McKennie", pos: "CM", age: 27 },
    ],
    "Lazio": [
      { name: "Alessio Furlanetto", pos: "GK", age: 24 },
      { name: "Christos Mandas", pos: "GK" },
      { name: "Edoardo Motta", pos: "GK" },
      { name: "Giacomo Giacomone", pos: "GK", age: 17 },
      { name: "Ivan Provedel", pos: "GK", age: 32 },
      { name: "Nicolò Pannozzo", pos: "GK", age: 18 },
    ],
    "Mainz": [
      { name: "Armindo Sieb", pos: "FW", age: 23 },
      { name: "Daniel Batz", pos: "GK", age: 35 },
      { name: "Danny da Costa", pos: "CB", age: 32 },
      { name: "Dominik Kohr", pos: "CM", age: 32 },
      { name: "Kacper Potulski", pos: "FB", age: 18 },
      { name: "Lee Jae-Sung", pos: "CM", age: 33 },
      { name: "Nadiem Amiri", pos: "DM", age: 29 },
      { name: "Paul Nebel", pos: "CM", age: 23 },
      { name: "Phillip Tietz", pos: "FW", age: 28 },
      { name: "Phillipp Mwene", pos: "FB", age: 32 },
      { name: "Sheraldo Becker", pos: "FW", age: 31 },
      { name: "Silvan Widmer", pos: "FB", age: 33 },
      { name: "Stefan Bell", pos: "CB", age: 34 },
    ],
    "Mallorca": [
      { name: "Abdón Prats", pos: "FW", age: 33 },
      { name: "Antonio Raíllo", pos: "FB", age: 34 },
      { name: "Antonio Sánchez", pos: "AM", age: 29 },
      { name: "Iván Cuéllar", pos: "GK", age: 42 },
      { name: "Jan Virgili", pos: "WG", age: 19 },
      { name: "Leo Román", pos: "GK", age: 25 },
      { name: "Lucas Bergstrom", pos: "GK", age: 23 },
      { name: "Nil Torreguitart", pos: "GK", age: 24 },
      { name: "Pablo Maffeo", pos: "FB", age: 28 },
      { name: "Pablo Torre", pos: "CM", age: 23 },
      { name: "Rares Vlad", pos: "GK", age: 20 },
      { name: "Rimvydas Kiriejevas", pos: "GK", age: 22 },
      { name: "Samú Costa", pos: "AM", age: 25 },
      { name: "Vedat Muriqi", pos: "FW", age: 32 },
    ],
    "Minnesota United": [
      { name: "Dayne St. Clair", pos: "GK", age: 27 },
      { name: "Alec Smir", pos: "GK", age: 25 },
      { name: "Jefferson Díaz", pos: "CB", age: 24 },
      { name: "Kipp Keller", pos: "CB", age: 24 },
      { name: "Mikael Marqués", pos: "CB", age: 23 },
    ],
    "New York Red Bulls": [
      { name: "Carlos Coronel", pos: "GK", age: 28 },
      { name: "AJ Marcucci", pos: "GK", age: 26 },
      { name: "John McCarthy", pos: "GK", age: 33 },
      { name: "Aidan Stokes", pos: "GK", age: 17 },
      { name: "Tobias Szewczyk", pos: "GK", age: 16 },
      { name: "Noah Eile", pos: "CB", age: 23 },
      { name: "Alexander Hack", pos: "CB", age: 32 },
      { name: "Tim Parker", pos: "CB", age: 32 },
      { name: "Kyle Duncan", pos: "FB", age: 28 },
      { name: "Raheem Edwards", pos: "FB", age: 30 },
      { name: "Juan Mina", pos: "FB", age: 21 },
      { name: "Dylan Nealis", pos: "FB", age: 27 },
      { name: "Curtis Ofori", pos: "FB", age: 20 },
      { name: "Omar Valencia", pos: "FB", age: 21 },
      { name: "Gustav Berggren", pos: "DM", age: 28 },
      { name: "Ronald Donkor", pos: "CM", age: 22 },
      { name: "Daniel Edelman", pos: "DM", age: 22 },
    ],
    "Osasuna": [
      { name: "Abel Bretones", pos: "FB", age: 25 },
      { name: "Aimar Oroz", pos: "CM", age: 24 },
      { name: "Aitor Fernández", pos: "GK", age: 35 },
      { name: "Alejandro Catena", pos: "CB", age: 31 },
      { name: "Ante Budimir", pos: "WG", age: 34 },
      { name: "Asier Osambela", pos: "CM", age: 21 },
      { name: "Dimitrios Stamatakis", pos: "GK", age: 23 },
      { name: "Enrique Barja", pos: "WG", age: 29 },
      { name: "Enzo Boyomo", pos: "CB", age: 24 },
      { name: "Iker Benito", pos: "FW", age: 23 },
      { name: "Rafael Fernández Rodríguez", pos: "GK", age: 22 },
      { name: "Rubén García", pos: "DM", age: 32 },
      { name: "Sergio Herrera", pos: "GK", age: 33 },
      { name: "Valentin Rosier", pos: "FB", age: 29 },
    ],
    "Philadelphia Union": [
      { name: "Oliver Semmle", pos: "GK", age: 26 },
      { name: "Alejandro Bedoya", pos: "CM", age: 37 },
      { name: "Dániel Gazdag", pos: "AM", age: 28 },
      { name: "Jakob Glesnes", pos: "CB", age: 30 },
      { name: "Mikael Uhre", pos: "FW", age: 30 },
    ],
    "RB Leipzig": [
      { name: "Antonio Nusa", pos: "CM", age: 21 },
      { name: "Assan Ouédraogo", pos: "AM", age: 20 },
      { name: "Ayodele Thomas", pos: "WG", age: 18 },
      { name: "Benjamin Henrichs", pos: "FB", age: 29 },
      { name: "Christoph Baumgartner", pos: "AM", age: 26 },
      { name: "Conrad Harder", pos: "WG", age: 21 },
      { name: "David Raum", pos: "CB", age: 28 },
      { name: "Johan Bakayoko", pos: "FW", age: 23 },
      { name: "Leopold Zingerle", pos: "GK", age: 32 },
      { name: "Ridle Baku", pos: "FB", age: 28 },
      { name: "Rômulo", pos: "FW", age: 24 },
      { name: "Willi Orbán", pos: "FB", age: 33 },
      { name: "Xaver Schlager", pos: "AM", age: 28 },
      { name: "Yan Diomande", pos: "FW", age: 19 },
    ],
    "Rayo Vallecano": [
      { name: "Adrián Molina", pos: "GK", age: 20 },
      { name: "Alemão", pos: "WG", age: 28 },
      { name: "Álvaro García", pos: "AM", age: 33 },
      { name: "Augusto Batalla", pos: "GK", age: 30 },
      { name: "Daniel Cárdenas", pos: "GK", age: 29 },
      { name: "Florian Lejeune", pos: "CB", age: 35 },
      { name: "Fran Pérez", pos: "CM", age: 23 },
      { name: "Isi Palazón", pos: "CM", age: 31 },
      { name: "Jorge de Frutos", pos: "FW", age: 29 },
      { name: "Juan Pedro Gil Bueno", pos: "GK", age: 25 },
      { name: "Nobel Mendy", pos: "CB", age: 21 },
      { name: "Pathé Ciss", pos: "CM", age: 32 },
      { name: "Randy Nteka", pos: "DM", age: 28 },
      { name: "Sergio Camello", pos: "WG", age: 25 },
    ],
    "Real Betis": [
      { name: "Abde Ezzalzouli", pos: "FW", age: 24 },
      { name: "Adrián", pos: "GK", age: 39 },
      { name: "Aitor Ruibal", pos: "WG", age: 30 },
      { name: "Álvaro Valles", pos: "GK", age: 28 },
      { name: "Antony", pos: "WG", age: 26 },
      { name: "Cédric Bakambu", pos: "FW", age: 35 },
      { name: "Cucho Hernández", pos: "WG", age: 27 },
      { name: "Germán García", pos: "GK", age: 22 },
      { name: "Giovani Lo Celso", pos: "CM", age: 30 },
      { name: "Gonzalo Petit", pos: "WG", age: 19 },
      { name: "Guilherme Fernandes", pos: "GK", age: 25 },
      { name: "Héctor Bellerín", pos: "CB", age: 31 },
      { name: "Manu González", pos: "GK", age: 19 },
      { name: "Pablo Fornals", pos: "CM", age: 30 },
    ],
    "Real Madrid": [
      { name: "Álvaro Carreras", pos: "CB", age: 23 },
      { name: "Álvaro González", pos: "GK", age: 19 },
      { name: "Andriy Lunin", pos: "GK", age: 27 },
      { name: "Arda Güler", pos: "CM", age: 21 },
      { name: "Dean Huijsen", pos: "FB", age: 21 },
      { name: "Éder Militão", pos: "FB", age: 28 },
      { name: "Federico Valverde", pos: "CM", age: 27 },
      { name: "Fran González", pos: "GK", age: 20 },
      { name: "Gonzalo García", pos: "WG", age: 22 },
      { name: "Javier Navarro", pos: "GK", age: 19 },
      { name: "Jude Bellingham", pos: "CM", age: 22 },
      { name: "Kylian Mbappé", pos: "WG", age: 27 },
      { name: "Sergio Mestre", pos: "GK", age: 21 },
      { name: "Vinícius Júnior", pos: "FW", age: 25 },
    ],
    "Real Salt Lake": [
      { name: "Rafael Cabral", pos: "GK", age: 33 },
      { name: "Max Kerkvliet", pos: "GK", age: 18 },
      { name: "Zac MacMath", pos: "GK", age: 32 },
      { name: "Mason Stajduhar", pos: "GK", age: 26 },
      { name: "Javain Brown", pos: "FB", age: 24 },
      { name: "Zack Farnsworth", pos: "CB", age: 21 },
      { name: "Justen Glad", pos: "CB", age: 26 },
      { name: "Philip Quinton", pos: "CB", age: 24 },
      { name: "Luis Rivera", pos: "FB", age: 16 },
      { name: "Tommy Silva", pos: "FB", age: 21 },
      { name: "Sam Junqua", pos: "FB", age: 27 },
      { name: "Gio Villa", pos: "FB", age: 17 },
      { name: "DeAndre Yedlin", pos: "FB", age: 31 },
      { name: "Noel Caliskan", pos: "CM", age: 25 },
      { name: "Griffin Dillon", pos: "CM", age: 20 },
      { name: "Kevon Lambert", pos: "DM", age: 27 },
      { name: "Diego Luna", pos: "WG", age: 21 },
      { name: "Luca Moisa", pos: "CM", age: 17 },
      { name: "Nelson Palacio", pos: "CM", age: 23 },
      { name: "Pablo Ruiz", pos: "CM", age: 26 },
      { name: "Jude Wellings", pos: "CM", age: 19 },
      { name: "Forster Ajago", pos: "FW", age: 22 },
      { name: "Jesús Barea", pos: "FW", age: 23 },
      { name: "Matthew Bell", pos: "WG", age: 23 },
      { name: "Rwan Cruz", pos: "FW", age: 22 },
      { name: "Aiden Hezarkhani", pos: "WG", age: 18 },
      { name: "Omar Marquez", pos: "WG", age: 17 },
      { name: "Johnny Russell", pos: "WG", age: 35 },
      { name: "Tyler Wolff", pos: "WG", age: 22 },
      { name: "Marcos Zambrano", pos: "FW", age: 20 },
      { name: "Zavier Gozo", pos: "WG", age: 18 },
    ],
    "Real Sociedad": [
      { name: "Aihen Muñoz", pos: "CB", age: 28 },
      { name: "Aitor Fraga", pos: "GK", age: 23 },
      { name: "Álex Remiro", pos: "GK", age: 31 },
      { name: "Alex Lebarbier", pos: "DM", age: 21 },
      { name: "Alex Marchal", pos: "FW", age: 18 },
      { name: "Ander Barrenetxea", pos: "FW", age: 24 },
      { name: "Brais Méndez", pos: "CM", age: 29 },
      { name: "Carlos Soler", pos: "DM", age: 29 },
      { name: "Gonçalo Guedes", pos: "FW", age: 29 },
      { name: "Luka Sucic", pos: "CM", age: 23 },
      { name: "Mikel Oyarzabal", pos: "FW", age: 29 },
      { name: "Orri Óskarsson", pos: "WG", age: 21 },
      { name: "Theo Folgado", pos: "GK", age: 21 },
      { name: "Unai Marrero", pos: "GK", age: 24 },
    ],
    "San Jose Earthquakes": [
      { name: "Earl Edwards Jr.", pos: "GK", age: 33 },
      { name: "Cristian Arango", pos: "FW", age: 30 },
      { name: "Josef Martínez", pos: "FW", age: 32 },
      { name: "Mark-Anthony Kaye", pos: "CM", age: 30 },
    ],
    "Sevilla": [
      { name: "Akor Adams", pos: "FW", age: 26 },
      { name: "Alberto Flores", pos: "GK", age: 22 },
      { name: "Alexis Sánchez", pos: "FW", age: 37 },
      { name: "Alfonso González", pos: "FW", age: 27 },
      { name: "Andrés Castrín", pos: "FB", age: 23 },
      { name: "Djibril Sow", pos: "CM", age: 29 },
      { name: "Enrique Salas", pos: "CB", age: 24 },
      { name: "Isaac Romero", pos: "FW", age: 26 },
      { name: "Lorenzo Luchino", pos: "GK", age: 20 },
      { name: "Neal Maupay", pos: "FW", age: 29 },
      { name: "Nemanja Gudelj", pos: "CM", age: 34 },
      { name: "Oso", pos: "CB", age: 22 },
      { name: "Peque", pos: "WG", age: 23 },
      { name: "Rafa Mir", pos: "FW", age: 29 },
    ],
    "Sporting KC": [
      { name: "Ryan Schewe", pos: "GK" },
      { name: "Jacob Bartlett", pos: "DM" },
      { name: "Jansen Miller", pos: "CB", age: 23 },
    ],
    "Toronto FC": [
      { name: "Luka Gavran", pos: "GK", age: 25 },
      { name: "Sean Johnson", pos: "GK", age: 36 },
      { name: "Kevin Long", pos: "CB", age: 35 },
      { name: "Raoul Petretta", pos: "FB", age: 28 },
      { name: "Sigurd Rosted", pos: "CB", age: 31 },
      { name: "Henry Wingo", pos: "FB", age: 30 },
      { name: "Alonso Coello", pos: "CM", age: 26 },
      { name: "José Cifuentes", pos: "CM", age: 26 },
      { name: "Maxime Dominguez", pos: "AM", age: 29 },
      { name: "Deybi Flores", pos: "DM", age: 29 },
      { name: "Matty Longstaff", pos: "CM", age: 25 },
      { name: "Djordje Mihailovic", pos: "AM", age: 27 },
      { name: "Jonathan Osorio", pos: "CM", age: 33 },
      { name: "Derrick Etienne Jr.", pos: "WG", age: 29 },
      { name: "Lorenzo Insigne", pos: "WG", age: 34 },
      { name: "Richie Laryea", pos: "FB", age: 30 },
      { name: "Ola Brynhildsen", pos: "FW", age: 26 },
      { name: "Charlie Sharp", pos: "FW" },
      { name: "Tyrese Spicer", pos: "WG", age: 25 },
    ],
    "Union Berlin": [
      { name: "Danilho Doekhi", pos: "FB" },
      { name: "Ilyas Ansah", pos: "FW" },
      { name: "Jeong Woo-Yeong", pos: "CB" },
      { name: "Leopold Querfeld", pos: "CB" },
      { name: "Oliver Burke", pos: "FW" },
      { name: "Rani Khedira", pos: "CM" },
    ],
    "Valencia": [
      { name: "Aaron Mayol", pos: "FB", age: 18 },
      { name: "Aimar Blázquez", pos: "WG", age: 20 },
      { name: "Alejandro Panach Olmo", pos: "CB", age: 20 },
      { name: "Arnaut Danjuma", pos: "FW", age: 29 },
      { name: "Cristian Rivero", pos: "GK", age: 28 },
      { name: "Diego López", pos: "FW", age: 24 },
      { name: "Guido Rodríguez", pos: "CM", age: 32 },
      { name: "Hugo Duro", pos: "FW", age: 26 },
      { name: "Javi Guerra", pos: "CM", age: 23 },
      { name: "Largie Ramazani", pos: "WG", age: 25 },
      { name: "Pere García Bauzá", pos: "GK", age: 24 },
      { name: "Stole Dimitrievski", pos: "GK", age: 32 },
      { name: "Umar Sadiq", pos: "WG", age: 29 },
      { name: "Vicent Abril Sanz", pos: "GK", age: 21 },
    ],
    "Villarreal": [
      { name: "Alassane Diatta", pos: "DM", age: 21 },
      { name: "Alberto Moleiro", pos: "CM", age: 22 },
      { name: "Alex Fores", pos: "WG", age: 25 },
      { name: "Arnau Tenas", pos: "GK", age: 25 },
      { name: "Ayoze Pérez", pos: "FW", age: 32 },
      { name: "Diego Conde", pos: "GK", age: 27 },
      { name: "Georges Mikautadze", pos: "FW", age: 25 },
      { name: "Gerard Moreno", pos: "WG", age: 34 },
      { name: "Luiz Júnior", pos: "GK", age: 25 },
      { name: "Nicolas Pépé", pos: "WG", age: 31 },
      { name: "Pape Gueye", pos: "AM", age: 27 },
      { name: "Rubén Gómez", pos: "GK", age: 24 },
      { name: "Santi Comesaña", pos: "DM", age: 29 },
      { name: "Tajon Buchanan", pos: "FW", age: 27 },
    ],
  };

  MG.dataIntl = { REAL_SQUADS_INTL };
})(typeof globalThis !== "undefined" ? globalThis : this);
